/* Generated By:JJTree: Do not edit this line. ASTcondition_list.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcondition_list extends SimpleNode {
  public ASTcondition_list(int id) {
    super(id);
  }

  public ASTcondition_list(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ddc87bae9c4d5815151f13eb3f6c54c4 (do not edit this line) */
