/* Generated By:JJTree: Do not edit this line. ASTPrint_ln.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPrint_ln extends SimpleNode {
  public ASTPrint_ln(int id) {
    super(id);
  }

  public ASTPrint_ln(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ff5c02b98c8a7e5472d85e99777b67a6 (do not edit this line) */
