/* Generated By:JJTree: Do not edit this line. ASTvec_const.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvec_const extends SimpleNode {
  public ASTvec_const(int id) {
    super(id);
  }

  public ASTvec_const(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8786ede86988f4e153c1240c64e0c96d (do not edit this line) */
