/* Generated By:JavaCC: Do not edit this line. VNMDefaultVisitor.java Version 7.0.9 */
public class VNMDefaultVisitor implements VNMVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTbody node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTclause node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTvar_decl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTfn_decl node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTident_list node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTfn_call node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTidnum node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTidvec node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTboolean_call node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTidbool node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTexp_list node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTcondition_list node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTReturn node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPrint node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPrint_ln node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTstring node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAssign node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTIf node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNULL node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFor node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhile node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTor node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTand node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTnot node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTcomparison node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTle node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTleq node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTgre node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTgeq node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTeq node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTneq node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTin node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTnotin node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTneg node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTsum node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTpos node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTmul node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTdiv node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTmod node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTnumber node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTvec_const node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTRUE node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFALSE node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=131ce326ae8b77b905a0a26c59a705ca (do not edit this line) */
