/* Generated By:JJTree: Do not edit this line. ASTAssign.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssign extends SimpleNode {
  public ASTAssign(int id) {
    super(id);
  }

  public ASTAssign(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9f5bac3a23e08a8170945a18513ac10c (do not edit this line) */
