/* Generated By:JJTree: Do not edit this line. ASTboolean_call.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTboolean_call extends SimpleNode {
  public ASTboolean_call(int id) {
    super(id);
  }

  public ASTboolean_call(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=633f7dc786a9a8676b5a80b6f95bc91d (do not edit this line) */
