/* Generated By:JJTree: Do not edit this line. ASTfn_call.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfn_call extends SimpleNode {
  public ASTfn_call(int id) {
    super(id);
  }

  public ASTfn_call(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6b8a4d2f7d6c6e3ecf2e520fcf03becf (do not edit this line) */
