/* Generated By:JJTree: Do not edit this line. ASTident_list.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTident_list extends SimpleNode {
  public ASTident_list(int id) {
    super(id);
  }

  public ASTident_list(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=68b8f22d8e5e2d23ad9b0acf7e6aac79 (do not edit this line) */
