/* Generated By:JJTree: Do not edit this line. ASTneq.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTneq extends SimpleNode {
  public ASTneq(int id) {
    super(id);
  }

  public ASTneq(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ec84e11a7b032c1cadd91640d6e0cac7 (do not edit this line) */
