/* Generated By:JJTree: Do not edit this line. ASTnot.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTnot extends SimpleNode {
  public ASTnot(int id) {
    super(id);
  }

  public ASTnot(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5647c5ab3c0d194d85e61d5906d31578 (do not edit this line) */
