/* Generated By:JJTree: Do not edit this line. ASTPrint_ln.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPrint_ln extends SimpleNode {
  public ASTPrint_ln(int id) {
    super(id);
  }

  public ASTPrint_ln(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9b584ab7dad3926d8faa7bbfe781a779 (do not edit this line) */
