/* Generated By:JJTree: Do not edit this line. ASTvec_const.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTvec_const extends SimpleNode {
  public ASTvec_const(int id) {
    super(id);
  }

  public ASTvec_const(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5f3d7013e6eebaeef35a8b0f4ee65dd4 (do not edit this line) */
