/* Generated By:JavaCC: Do not edit this line. VNMVisitor.java Version 7.0.9 */
public interface VNMVisitor
{
  public Object visit(SimpleNode node, Object data) throws Exception;
  public Object visit(ASTbody node, Object data) throws Exception;
  public Object visit(ASTclause node, Object data) throws Exception;
  public Object visit(ASTvar_decl node, Object data) throws Exception;
  public Object visit(ASTfn_decl node, Object data) throws Exception;
  public Object visit(ASTident_list node, Object data) throws Exception;
  public Object visit(ASTfn_call node, Object data) throws Exception;
  public Object visit(ASTboolean_call node, Object data) throws Exception;
  public Object visit(ASTexp_list node, Object data) throws Exception;
  public Object visit(ASTcondition_list node, Object data) throws Exception;
  public Object visit(ASTReturn node, Object data) throws Exception;
  public Object visit(ASTPrint node, Object data) throws Exception;
  public Object visit(ASTPrint_ln node, Object data) throws Exception;
  public Object visit(ASTAssign node, Object data) throws Exception;
  public Object visit(ASTIf node, Object data) throws Exception;
  public Object visit(ASTNULL node, Object data) throws Exception;
  public Object visit(ASTFor node, Object data) throws Exception;
  public Object visit(ASTWhile node, Object data) throws Exception;
  public Object visit(ASTor node, Object data) throws Exception;
  public Object visit(ASTand node, Object data) throws Exception;
  public Object visit(ASTnot node, Object data) throws Exception;
  public Object visit(ASTcomparison node, Object data) throws Exception;
  public Object visit(ASTle node, Object data) throws Exception;
  public Object visit(ASTleq node, Object data) throws Exception;
  public Object visit(ASTgre node, Object data) throws Exception;
  public Object visit(ASTgeq node, Object data) throws Exception;
  public Object visit(ASTeq node, Object data) throws Exception;
  public Object visit(ASTneq node, Object data) throws Exception;
  public Object visit(ASTin node, Object data) throws Exception;
  public Object visit(ASTnotin node, Object data) throws Exception;
  public Object visit(ASTsum node, Object data) throws Exception;
  public Object visit(ASTneg node, Object data) throws Exception;
  public Object visit(ASTpos node, Object data) throws Exception;
  public Object visit(ASTmul node, Object data) throws Exception;
  public Object visit(ASTdiv node, Object data) throws Exception;
  public Object visit(ASTmod node, Object data) throws Exception;
  public Object visit(ASTvec_const node, Object data) throws Exception;
  public Object visit(ASTTRUE node, Object data) throws Exception;
  public Object visit(ASTFALSE node, Object data) throws Exception;
  public Object visit(ASTidvec node, Object data) throws Exception;
  public Object visit(ASTidnum node, Object data) throws Exception;
  public Object visit(ASTidbool node, Object data) throws Exception;
  public Object visit(ASTnumber node, Object data) throws Exception;
  public Object visit(ASTstring node, Object data) throws Exception;
}
/* JavaCC - OriginalChecksum=a4e9091c5fe546655bc58b00d3ba5c0f (do not edit this line) */
