/* VNM.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. VNM.java */
public class VNM/*@bgen(jjtree)*/implements VNMTreeConstants, VNMConstants {/*@bgen(jjtree)*/
  protected static JJTVNMState jjtree = new JJTVNMState();

/* ====================================================================
 * PARSER RULES
 * ==================================================================== */
  static final public 
SimpleNode start() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LRND:
    case LSQU:
    case MINUS:
    case PLUS:
    case WHILE:
    case FOR:
    case IF:
    case FUNCTION:
    case RETURN:
    case PRINT:
    case PRINTLN:
    case VAR:
    case NUMBER:
    case IDNUM:
    case IDBOOL:
    case IDVEC:{
      S();
{if ("" != null) return (SimpleNode) (jjtree.popNode());}
      break;
      }
    case 0:{
      jj_consume_token(0);
{if (true) throw new ParseException("End of File.");}
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public void S() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case WHILE:
    case FOR:
    case IF:
    case FUNCTION:
    case RETURN:
    case PRINT:
    case PRINTLN:
    case VAR:{
      statement_LL1();
      jj_consume_token(SCOL);
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      if (jj_2_1(2147483647)) {
        assign_stat();
        jj_consume_token(SCOL);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LRND:
        case LSQU:
        case MINUS:
        case PLUS:
        case NUMBER:
        case IDNUM:
        case IDVEC:{
          expression();
          jj_consume_token(SCOL);
          break;
          }
        case IDBOOL:{
          boolean_call();
          jj_consume_token(SCOL);
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}

  static final public void statement_LL1() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VAR:{
      var_decl();
      break;
      }
    case FUNCTION:{
      fn_decl();
      break;
      }
    case RETURN:{
      return_stat();
      break;
      }
    case PRINT:{
      print_stat();
      break;
      }
    case PRINTLN:{
      println_stat();
      break;
      }
    case IF:{
      if_stat();
      break;
      }
    case FOR:{
      for_stat();
      break;
      }
    case WHILE:{
      while_stat();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void statement() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case WHILE:
    case FOR:
    case IF:
    case FUNCTION:
    case RETURN:
    case PRINT:
    case PRINTLN:
    case VAR:{
      statement_LL1();
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      if (jj_2_2(2)) {
        fn_call();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDNUM:
        case IDBOOL:
        case IDVEC:{
          assign_stat();
          break;
          }
        default:
          jj_la1[5] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}

  static final public void body() throws ParseException {/*@bgen(jjtree) body */
  ASTbody jjtn000 = new ASTbody(JJTBODY);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case WHILE:
        case FOR:
        case IF:
        case FUNCTION:
        case RETURN:
        case PRINT:
        case PRINTLN:
        case VAR:
        case IDNUM:
        case IDBOOL:
        case IDVEC:{
          ;
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          break label_1;
        }
        statement();
        jj_consume_token(SCOL);
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void clause() throws ParseException {/*@bgen(jjtree) clause */
  ASTclause jjtn000 = new ASTclause(JJTCLAUSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      label_2:
      while (true) {
        statement();
        jj_consume_token(SCOL);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case WHILE:
        case FOR:
        case IF:
        case FUNCTION:
        case RETURN:
        case PRINT:
        case PRINTLN:
        case VAR:
        case IDNUM:
        case IDBOOL:
        case IDVEC:{
          ;
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          break label_2;
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void var_decl() throws ParseException {
    jj_consume_token(VAR);
    var_list();
}

  static final public void var_list() throws ParseException {
ASTvar_decl jjtn001 = new ASTvar_decl(JJTVAR_DECL);
    boolean jjtc001 = true;
    jjtree.openNodeScope(jjtn001);
    try {
      identifier();
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_3;
        }
        jj_consume_token(COMMA);
        identifier();
      }
    } catch (Throwable jjte001) {
if (jjtc001) {
      jjtree.clearNodeScope(jjtn001);
      jjtc001 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte001 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte001;}
    }
    if (jjte001 instanceof ParseException) {
      {if (true) throw (ParseException)jjte001;}
    }
    {if (true) throw (Error)jjte001;}
    } finally {
if (jjtc001) {
      jjtree.closeNodeScope(jjtn001, true);
    }
    }
}

  static final public void fn_decl() throws ParseException {/*@bgen(jjtree) fn_decl */
  ASTfn_decl jjtn000 = new ASTfn_decl(JJTFN_DECL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FUNCTION);
      identifier();
      jj_consume_token(LRND);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDNUM:
      case IDBOOL:
      case IDVEC:{
        ident_list();
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        ;
      }
      jj_consume_token(RRND);
      body();
      jj_consume_token(END);
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void ident_list() throws ParseException {/*@bgen(jjtree) ident_list */
  ASTident_list jjtn000 = new ASTident_list(JJTIDENT_LIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      identifier();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          break label_4;
        }
        jj_consume_token(COMMA);
        identifier();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void fn_call() throws ParseException {/*@bgen(jjtree) fn_call */
  ASTfn_call jjtn000 = new ASTfn_call(JJTFN_CALL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDNUM:{
        idnum();
        jj_consume_token(LRND);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LRND:
        case LSQU:
        case MINUS:
        case PLUS:
        case NUMBER:
        case IDNUM:
        case IDVEC:{
          exp_list();
          break;
          }
        default:
          jj_la1[11] = jj_gen;
          ;
        }
        jj_consume_token(RRND);
        break;
        }
      case IDVEC:{
        idvec();
        jj_consume_token(LRND);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LRND:
        case LSQU:
        case MINUS:
        case PLUS:
        case NUMBER:
        case IDNUM:
        case IDVEC:{
          exp_list();
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          ;
        }
        jj_consume_token(RRND);
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

  static final public void boolean_call() throws ParseException {/*@bgen(jjtree) boolean_call */
  ASTboolean_call jjtn000 = new ASTboolean_call(JJTBOOLEAN_CALL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      idbool();
      jj_consume_token(LRND);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LRND:
      case LSQU:
      case MINUS:
      case PLUS:
      case NUMBER:
      case IDNUM:
      case IDVEC:{
        exp_list();
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        ;
      }
      jj_consume_token(RRND);
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void exp_list() throws ParseException {/*@bgen(jjtree) exp_list */
  ASTexp_list jjtn000 = new ASTexp_list(JJTEXP_LIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      expression();
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[15] = jj_gen;
          break label_5;
        }
        jj_consume_token(COMMA);
        expression();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

// Explicit condition list for vector constants
  static final public void condition_list() throws ParseException {/*@bgen(jjtree) condition_list */
  ASTcondition_list jjtn000 = new ASTcondition_list(JJTCONDITION_LIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      condition();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[16] = jj_gen;
          break label_6;
        }
        jj_consume_token(COMMA);
        condition();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void return_stat() throws ParseException {/*@bgen(jjtree) Return */
  ASTReturn jjtn000 = new ASTReturn(JJTRETURN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(RETURN);
      returnval();
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void returnval() throws ParseException {
    if (jj_2_3(2147483647)) {
      condition();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LRND:
      case LSQU:
      case MINUS:
      case PLUS:
      case NUMBER:
      case IDNUM:
      case IDVEC:{
        expression();
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  static final public void print_stat() throws ParseException {/*@bgen(jjtree) Print */
  ASTPrint jjtn000 = new ASTPrint(JJTPRINT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(PRINT);
      print_list();
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void println_stat() throws ParseException {/*@bgen(jjtree) Print_ln */
  ASTPrint_ln jjtn000 = new ASTPrint_ln(JJTPRINT_LN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(PRINTLN);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LRND:
      case LSQU:
      case MINUS:
      case PLUS:
      case STRING:
      case NUMBER:
      case IDNUM:
      case IDBOOL:
      case IDVEC:{
        print_list();
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void print_list() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LRND:
    case LSQU:
    case MINUS:
    case PLUS:
    case NUMBER:
    case IDNUM:
    case IDVEC:{
      expression();
      break;
      }
    case STRING:{
      string();
      break;
      }
    case IDBOOL:{
      idbool();
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        break label_7;
      }
      jj_consume_token(COMMA);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LRND:
      case LSQU:
      case MINUS:
      case PLUS:
      case NUMBER:
      case IDNUM:
      case IDVEC:{
        expression();
        break;
        }
      case STRING:{
        string();
        break;
        }
      case IDBOOL:{
        idbool();
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  static final public void assign_stat() throws ParseException {/*@bgen(jjtree) Assign */
  ASTAssign jjtn000 = new ASTAssign(JJTASSIGN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDNUM:{
        idnum();
        jj_consume_token(ASSGN);
        expression();
        break;
        }
      case IDBOOL:{
        idbool();
        jj_consume_token(ASSGN);
        condition();
        break;
        }
      case IDVEC:{
        idvec();
        jj_consume_token(ASSGN);
        vec_const();
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/* --- Control Flow --- */
  static final public 
void if_stat() throws ParseException {/*@bgen(jjtree) If */
  ASTIf jjtn000 = new ASTIf(JJTIF);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(IF);
      condition();
      jj_consume_token(THEN);
      clause();
      else_clause();
      jj_consume_token(FI);
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void else_clause() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELIF:{
ASTIf jjtn001 = new ASTIf(JJTIF);
      boolean jjtc001 = true;
      jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(ELIF);
        condition();
        jj_consume_token(THEN);
        clause();
        else_clause();
      } catch (Throwable jjte001) {
if (jjtc001) {
        jjtree.clearNodeScope(jjtn001);
        jjtc001 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte001 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte001;}
      }
      if (jjte001 instanceof ParseException) {
        {if (true) throw (ParseException)jjte001;}
      }
      {if (true) throw (Error)jjte001;}
      } finally {
if (jjtc001) {
        jjtree.closeNodeScope(jjtn001, true);
      }
      }
      break;
      }
    case ELSE:{
      jj_consume_token(ELSE);
      clause();
      break;
      }
    default:
      jj_la1[23] = jj_gen;
ASTNULL jjtn002 = new ASTNULL(JJTNULL);
      boolean jjtc002 = true;
      jjtree.openNodeScope(jjtn002);
      try {
jjtree.closeNodeScope(jjtn002, true);
      jjtc002 = false;

      } finally {
if (jjtc002) {
        jjtree.closeNodeScope(jjtn002, true);
      }
      }
    }
}

  static final public void for_stat() throws ParseException {/*@bgen(jjtree) For */
  ASTFor jjtn000 = new ASTFor(JJTFOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FOR);
      idnum();
      jj_consume_token(IN);
      exp_list();
      jj_consume_token(DO);
      body();
      jj_consume_token(END);
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void while_stat() throws ParseException {/*@bgen(jjtree) While */
  ASTWhile jjtn000 = new ASTWhile(JJTWHILE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(WHILE);
      condition();
      jj_consume_token(DO);
      body();
      jj_consume_token(END);
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

/* --- Logic & Conditions --- */
  static final public 
void condition() throws ParseException {
ASTor jjtn001 = new ASTor(JJTOR);
    boolean jjtc001 = true;
    jjtree.openNodeScope(jjtn001);
    try {
      and_clause();
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case VBAR:{
          ;
          break;
          }
        default:
          jj_la1[24] = jj_gen;
          break label_8;
        }
        jj_consume_token(VBAR);
        and_clause();
      }
    } catch (Throwable jjte001) {
if (jjtc001) {
      jjtree.clearNodeScope(jjtn001);
      jjtc001 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte001 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte001;}
    }
    if (jjte001 instanceof ParseException) {
      {if (true) throw (ParseException)jjte001;}
    }
    {if (true) throw (Error)jjte001;}
    } finally {
if (jjtc001) {
      jjtree.closeNodeScope(jjtn001, jjtree.nodeArity() > 1);
    }
    }
}

  static final public void and_clause() throws ParseException {
ASTand jjtn001 = new ASTand(JJTAND);
    boolean jjtc001 = true;
    jjtree.openNodeScope(jjtn001);
    try {
      not_clause();
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case AND:{
          ;
          break;
          }
        default:
          jj_la1[25] = jj_gen;
          break label_9;
        }
        jj_consume_token(AND);
        not_clause();
      }
    } catch (Throwable jjte001) {
if (jjtc001) {
      jjtree.clearNodeScope(jjtn001);
      jjtc001 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte001 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte001;}
    }
    if (jjte001 instanceof ParseException) {
      {if (true) throw (ParseException)jjte001;}
    }
    {if (true) throw (Error)jjte001;}
    } finally {
if (jjtc001) {
      jjtree.closeNodeScope(jjtn001, jjtree.nodeArity() > 1);
    }
    }
}

  static final public void not_clause() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NOT:{
      jj_consume_token(NOT);
ASTnot jjtn001 = new ASTnot(JJTNOT);
          boolean jjtc001 = true;
          jjtree.openNodeScope(jjtn001);
      try {
        not_clause();
      } catch (Throwable jjte001) {
if (jjtc001) {
            jjtree.clearNodeScope(jjtn001);
            jjtc001 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte001 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte001;}
          }
          if (jjte001 instanceof ParseException) {
            {if (true) throw (ParseException)jjte001;}
          }
          {if (true) throw (Error)jjte001;}
      } finally {
if (jjtc001) {
            jjtree.closeNodeScope(jjtn001, true);
          }
      }
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      if (jj_2_4(2147483647)) {
        comparison();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LRND:{
          jj_consume_token(LRND);
          condition();
          jj_consume_token(RRND);
          break;
          }
        default:
          jj_la1[27] = jj_gen;
          if (jj_2_5(2)) {
            boolean_call();
          } else {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case FALSE:
            case TRUE:
            case IDBOOL:{
              bool_simple();
              break;
              }
            default:
              jj_la1[28] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
        }
      }
    }
}

  static final public void comparison() throws ParseException {/*@bgen(jjtree) comparison */
  ASTcomparison jjtn000 = new ASTcomparison(JJTCOMPARISON);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      expression();
      comparator();
      expression();
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void comparator() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LESS:{
ASTle jjtn001 = new ASTle(JJTLE);
      boolean jjtc001 = true;
      jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(LESS);
      } finally {
if (jjtc001) {
        jjtree.closeNodeScope(jjtn001, true);
      }
      }
      break;
      }
    case LE:{
ASTleq jjtn002 = new ASTleq(JJTLEQ);
      boolean jjtc002 = true;
      jjtree.openNodeScope(jjtn002);
      try {
        jj_consume_token(LE);
      } finally {
if (jjtc002) {
        jjtree.closeNodeScope(jjtn002, true);
      }
      }
      break;
      }
    case GREAT:{
ASTgre jjtn003 = new ASTgre(JJTGRE);
      boolean jjtc003 = true;
      jjtree.openNodeScope(jjtn003);
      try {
        jj_consume_token(GREAT);
      } finally {
if (jjtc003) {
        jjtree.closeNodeScope(jjtn003, true);
      }
      }
      break;
      }
    case GE:{
ASTgeq jjtn004 = new ASTgeq(JJTGEQ);
      boolean jjtc004 = true;
      jjtree.openNodeScope(jjtn004);
      try {
        jj_consume_token(GE);
      } finally {
if (jjtc004) {
        jjtree.closeNodeScope(jjtn004, true);
      }
      }
      break;
      }
    case EQ:{
ASTeq jjtn005 = new ASTeq(JJTEQ);
      boolean jjtc005 = true;
      jjtree.openNodeScope(jjtn005);
      try {
        jj_consume_token(EQ);
      } finally {
if (jjtc005) {
        jjtree.closeNodeScope(jjtn005, true);
      }
      }
      break;
      }
    case NEQ:{
ASTneq jjtn006 = new ASTneq(JJTNEQ);
      boolean jjtc006 = true;
      jjtree.openNodeScope(jjtn006);
      try {
        jj_consume_token(NEQ);
      } finally {
if (jjtc006) {
        jjtree.closeNodeScope(jjtn006, true);
      }
      }
      break;
      }
    case IN:{
ASTin jjtn007 = new ASTin(JJTIN);
      boolean jjtc007 = true;
      jjtree.openNodeScope(jjtn007);
      try {
        jj_consume_token(IN);
      } finally {
if (jjtc007) {
        jjtree.closeNodeScope(jjtn007, true);
      }
      }
      break;
      }
    case NOTIN:{
ASTnotin jjtn008 = new ASTnotin(JJTNOTIN);
      boolean jjtc008 = true;
      jjtree.openNodeScope(jjtn008);
      try {
        jj_consume_token(NOTIN);
      } finally {
if (jjtc008) {
        jjtree.closeNodeScope(jjtn008, true);
      }
      }
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

/* --- Arithmetic --- */
  static final public 
void expression() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:{
ASTsum jjtn001 = new ASTsum(JJTSUM);
      boolean jjtc001 = true;
      jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(PLUS);
        product();
        label_10:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case MINUS:
          case PLUS:{
            ;
            break;
            }
          default:
            jj_la1[30] = jj_gen;
            break label_10;
          }
          summand();
        }
      } catch (Throwable jjte001) {
if (jjtc001) {
        jjtree.clearNodeScope(jjtn001);
        jjtc001 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte001 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte001;}
      }
      if (jjte001 instanceof ParseException) {
        {if (true) throw (ParseException)jjte001;}
      }
      {if (true) throw (Error)jjte001;}
      } finally {
if (jjtc001) {
        jjtree.closeNodeScope(jjtn001, jjtree.nodeArity() > 1);
      }
      }
      break;
      }
    case MINUS:{
ASTsum jjtn002 = new ASTsum(JJTSUM);
      boolean jjtc002 = true;
      jjtree.openNodeScope(jjtn002);
      try {
        neg();
        label_11:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case MINUS:
          case PLUS:{
            ;
            break;
            }
          default:
            jj_la1[31] = jj_gen;
            break label_11;
          }
          summand();
        }
      } catch (Throwable jjte002) {
if (jjtc002) {
        jjtree.clearNodeScope(jjtn002);
        jjtc002 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte002 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte002;}
      }
      if (jjte002 instanceof ParseException) {
        {if (true) throw (ParseException)jjte002;}
      }
      {if (true) throw (Error)jjte002;}
      } finally {
if (jjtc002) {
        jjtree.closeNodeScope(jjtn002, true);
      }
      }
      break;
      }
    case LRND:
    case LSQU:
    case NUMBER:
    case IDNUM:
    case IDVEC:{
ASTsum jjtn003 = new ASTsum(JJTSUM);
      boolean jjtc003 = true;
      jjtree.openNodeScope(jjtn003);
      try {
        product();
        label_12:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case MINUS:
          case PLUS:{
            ;
            break;
            }
          default:
            jj_la1[32] = jj_gen;
            break label_12;
          }
          summand();
        }
      } catch (Throwable jjte003) {
if (jjtc003) {
        jjtree.clearNodeScope(jjtn003);
        jjtc003 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte003 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte003;}
      }
      if (jjte003 instanceof ParseException) {
        {if (true) throw (ParseException)jjte003;}
      }
      {if (true) throw (Error)jjte003;}
      } finally {
if (jjtc003) {
        jjtree.closeNodeScope(jjtn003, jjtree.nodeArity() > 1);
      }
      }
      break;
      }
    default:
      jj_la1[33] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void neg() throws ParseException {/*@bgen(jjtree) neg */
  ASTneg jjtn000 = new ASTneg(JJTNEG);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(MINUS);
      product();
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void summand() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:{
      jj_consume_token(PLUS);
ASTpos jjtn001 = new ASTpos(JJTPOS);
          boolean jjtc001 = true;
          jjtree.openNodeScope(jjtn001);
      try {
        product();
      } catch (Throwable jjte001) {
if (jjtc001) {
            jjtree.clearNodeScope(jjtn001);
            jjtc001 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte001 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte001;}
          }
          if (jjte001 instanceof ParseException) {
            {if (true) throw (ParseException)jjte001;}
          }
          {if (true) throw (Error)jjte001;}
      } finally {
if (jjtc001) {
            jjtree.closeNodeScope(jjtn001, true);
          }
      }
      break;
      }
    case MINUS:{
      jj_consume_token(MINUS);
ASTneg jjtn002 = new ASTneg(JJTNEG);
          boolean jjtc002 = true;
          jjtree.openNodeScope(jjtn002);
      try {
        product();
      } catch (Throwable jjte002) {
if (jjtc002) {
            jjtree.clearNodeScope(jjtn002);
            jjtc002 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte002 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte002;}
          }
          if (jjte002 instanceof ParseException) {
            {if (true) throw (ParseException)jjte002;}
          }
          {if (true) throw (Error)jjte002;}
      } finally {
if (jjtc002) {
            jjtree.closeNodeScope(jjtn002, true);
          }
      }
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void product() throws ParseException {
    term();
    moreterms();
}

  static final public void moreterms() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIMES:{
ASTmul jjtn001 = new ASTmul(JJTMUL);
      boolean jjtc001 = true;
      jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(TIMES);
        term();
      } catch (Throwable jjte001) {
if (jjtc001) {
        jjtree.clearNodeScope(jjtn001);
        jjtc001 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte001 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte001;}
      }
      if (jjte001 instanceof ParseException) {
        {if (true) throw (ParseException)jjte001;}
      }
      {if (true) throw (Error)jjte001;}
      } finally {
if (jjtc001) {
        jjtree.closeNodeScope(jjtn001,  2);
      }
      }
      moreterms();
      break;
      }
    case DIV:{
ASTdiv jjtn002 = new ASTdiv(JJTDIV);
      boolean jjtc002 = true;
      jjtree.openNodeScope(jjtn002);
      try {
        jj_consume_token(DIV);
        term();
      } catch (Throwable jjte002) {
if (jjtc002) {
        jjtree.clearNodeScope(jjtn002);
        jjtc002 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte002 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte002;}
      }
      if (jjte002 instanceof ParseException) {
        {if (true) throw (ParseException)jjte002;}
      }
      {if (true) throw (Error)jjte002;}
      } finally {
if (jjtc002) {
        jjtree.closeNodeScope(jjtn002,  2);
      }
      }
      moreterms();
      break;
      }
    case 54:{
ASTmod jjtn003 = new ASTmod(JJTMOD);
      boolean jjtc003 = true;
      jjtree.openNodeScope(jjtn003);
      try {
        jj_consume_token(54);
        term();
      } catch (Throwable jjte003) {
if (jjtc003) {
        jjtree.clearNodeScope(jjtn003);
        jjtc003 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte003 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte003;}
      }
      if (jjte003 instanceof ParseException) {
        {if (true) throw (ParseException)jjte003;}
      }
      {if (true) throw (Error)jjte003;}
      } finally {
if (jjtc003) {
        jjtree.closeNodeScope(jjtn003,  2);
      }
      }
      moreterms();
      break;
      }
    default:
      jj_la1[35] = jj_gen;

    }
}

  static final public void term() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LRND:{
      jj_consume_token(LRND);
      expression();
      jj_consume_token(RRND);
      break;
      }
    default:
      jj_la1[36] = jj_gen;
      if (jj_2_6(2)) {
        fn_call();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LSQU:
        case NUMBER:
        case IDNUM:
        case IDVEC:{
          simple_term();
          break;
          }
        default:
          jj_la1[37] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}

  static final public void simple_term() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDNUM:{
      idnum();
      break;
      }
    case IDVEC:{
      idvec();
      break;
      }
    case NUMBER:{
      number();
      break;
      }
    case LSQU:{
      vec_const();
      break;
      }
    default:
      jj_la1[38] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void vec_const() throws ParseException {/*@bgen(jjtree) vec_const */
  ASTvec_const jjtn000 = new ASTvec_const(JJTVEC_CONST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      if (jj_2_7(2147483647)) {
        jj_consume_token(LSQU);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LRND:
        case LSQU:
        case MINUS:
        case PLUS:
        case NUMBER:
        case IDNUM:
        case IDVEC:{
          exp_list();
          break;
          }
        default:
          jj_la1[39] = jj_gen;
          ;
        }
        jj_consume_token(RSQU);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LSQU:{
          jj_consume_token(LSQU);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case FALSE:
          case LRND:
          case LSQU:
          case MINUS:
          case NOT:
          case PLUS:
          case TRUE:
          case NUMBER:
          case IDNUM:
          case IDBOOL:
          case IDVEC:{
            condition_list();
            break;
            }
          default:
            jj_la1[40] = jj_gen;
            ;
          }
          jj_consume_token(RSQU);
          break;
          }
        default:
          jj_la1[41] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/* --- Terminals & Wrappers --- */
  static final public 
void identifier() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDNUM:{
      idnum();
      break;
      }
    case IDBOOL:{
      idbool();
      break;
      }
    case IDVEC:{
      idvec();
      break;
      }
    default:
      jj_la1[42] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void bool_simple() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDBOOL:{
      idbool();
      break;
      }
    case TRUE:{
ASTTRUE jjtn001 = new ASTTRUE(JJTTRUE);
      boolean jjtc001 = true;
      jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(TRUE);
      } finally {
if (jjtc001) {
        jjtree.closeNodeScope(jjtn001, true);
      }
      }
      break;
      }
    case FALSE:{
ASTFALSE jjtn002 = new ASTFALSE(JJTFALSE);
      boolean jjtc002 = true;
      jjtree.openNodeScope(jjtn002);
      try {
        jj_consume_token(FALSE);
      } finally {
if (jjtc002) {
        jjtree.closeNodeScope(jjtn002, true);
      }
      }
      break;
      }
    default:
      jj_la1[43] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void idvec() throws ParseException {/*@bgen(jjtree) idvec */
  ASTidvec jjtn000 = new ASTidvec(JJTIDVEC);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(IDVEC);
jjtree.closeNodeScope(jjtn000, true);
                  jjtc000 = false;
jjtn000.jjtSetValue(t.image);
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void idnum() throws ParseException {/*@bgen(jjtree) idnum */
  ASTidnum jjtn000 = new ASTidnum(JJTIDNUM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(IDNUM);
jjtree.closeNodeScope(jjtn000, true);
                  jjtc000 = false;
jjtn000.jjtSetValue(t.image);
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void idbool() throws ParseException {/*@bgen(jjtree) idbool */
  ASTidbool jjtn000 = new ASTidbool(JJTIDBOOL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(IDBOOL);
jjtree.closeNodeScope(jjtn000, true);
                   jjtc000 = false;
jjtn000.jjtSetValue(t.image);
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void number() throws ParseException {/*@bgen(jjtree) number */
  ASTnumber jjtn000 = new ASTnumber(JJTNUMBER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(NUMBER);
jjtree.closeNodeScope(jjtn000, true);
                   jjtc000 = false;
jjtn000.jjtSetValue(t.image);
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void string() throws ParseException {/*@bgen(jjtree) string */
  ASTstring jjtn000 = new ASTstring(JJTSTRING);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);Token t;
    try {
      t = jj_consume_token(STRING);
jjtree.closeNodeScope(jjtn000, true);
                   jjtc000 = false;
jjtn000.jjtSetValue(t.image);
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_3R_vec_const_370_10_82()
 {
    if (jj_3R_condition_list_197_3_83()) return true;
    return false;
  }

  static private boolean jj_3R_boolean_call_184_3_18()
 {
    if (jj_3R_idbool_406_3_37()) return true;
    if (jj_scan_token(LRND)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_boolean_call_184_17_64()) jj_scanpos = xsp;
    if (jj_scan_token(RRND)) return true;
    return false;
  }

  static private boolean jj_3R_vec_const_370_5_80()
 {
    if (jj_scan_token(LSQU)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_vec_const_370_10_82()) jj_scanpos = xsp;
    if (jj_scan_token(RSQU)) return true;
    return false;
  }

  static private boolean jj_3R_vec_const_369_5_79()
 {
    if (jj_scan_token(LSQU)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_vec_const_369_38_81()) jj_scanpos = xsp;
    if (jj_scan_token(RSQU)) return true;
    return false;
  }

  static private boolean jj_3R_vec_const_369_5_78()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_vec_const_369_5_79()) {
    jj_scanpos = xsp;
    if (jj_3R_vec_const_370_5_80()) return true;
    }
    return false;
  }

  static private boolean jj_3R_fn_call_178_5_23()
 {
    if (jj_3R_idvec_394_3_39()) return true;
    if (jj_scan_token(LRND)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_fn_call_178_18_76()) jj_scanpos = xsp;
    if (jj_scan_token(RRND)) return true;
    return false;
  }

  static private boolean jj_3R_fn_call_177_5_14()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_fn_call_177_5_22()) {
    jj_scanpos = xsp;
    if (jj_3R_fn_call_178_5_23()) return true;
    }
    return false;
  }

  static private boolean jj_3R_fn_call_177_5_22()
 {
    if (jj_3R_idnum_400_3_38()) return true;
    if (jj_scan_token(LRND)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_fn_call_177_18_75()) jj_scanpos = xsp;
    if (jj_scan_token(RRND)) return true;
    return false;
  }

  static private boolean jj_3R_simple_term_363_5_73()
 {
    if (jj_3R_vec_const_369_5_78()) return true;
    return false;
  }

  static private boolean jj_3R_simple_term_362_5_72()
 {
    if (jj_3R_number_412_3_77()) return true;
    return false;
  }

  static private boolean jj_3R_simple_term_361_5_71()
 {
    if (jj_3R_idvec_394_3_39()) return true;
    return false;
  }

  static private boolean jj_3R_simple_term_360_5_68()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_simple_term_360_5_70()) {
    jj_scanpos = xsp;
    if (jj_3R_simple_term_361_5_71()) {
    jj_scanpos = xsp;
    if (jj_3R_simple_term_362_5_72()) {
    jj_scanpos = xsp;
    if (jj_3R_simple_term_363_5_73()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_simple_term_360_5_70()
 {
    if (jj_3R_idnum_400_3_38()) return true;
    return false;
  }

  static private boolean jj_3R_term_354_5_57()
 {
    if (jj_3R_simple_term_360_5_68()) return true;
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_3R_fn_call_177_5_14()) return true;
    return false;
  }

  static private boolean jj_3R_term_352_5_51()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_term_352_5_56()) {
    jj_scanpos = xsp;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3R_term_354_5_57()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_term_352_5_56()
 {
    if (jj_scan_token(LRND)) return true;
    if (jj_3R_expression_316_5_16()) return true;
    if (jj_scan_token(RRND)) return true;
    return false;
  }

  static private boolean jj_3R_moreterms_346_5_60()
 {
    if (jj_scan_token(54)) return true;
    if (jj_3R_term_352_5_51()) return true;
    if (jj_3R_moreterms_343_5_52()) return true;
    return false;
  }

  static private boolean jj_3R_moreterms_346_5_61()
 {
    return false;
  }

  static private boolean jj_3R_moreterms_345_5_59()
 {
    if (jj_scan_token(DIV)) return true;
    if (jj_3R_term_352_5_51()) return true;
    if (jj_3R_moreterms_343_5_52()) return true;
    return false;
  }

  static private boolean jj_3R_moreterms_343_5_52()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_moreterms_343_5_58()) {
    jj_scanpos = xsp;
    if (jj_3R_moreterms_345_5_59()) {
    jj_scanpos = xsp;
    if (jj_3R_moreterms_346_5_60()) {
    jj_scanpos = xsp;
    if (jj_3R_moreterms_346_5_61()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_moreterms_343_5_58()
 {
    if (jj_scan_token(TIMES)) return true;
    if (jj_3R_term_352_5_51()) return true;
    if (jj_3R_moreterms_343_5_52()) return true;
    return false;
  }

  static private boolean jj_3R_product_337_3_42()
 {
    if (jj_3R_term_352_5_51()) return true;
    if (jj_3R_moreterms_343_5_52()) return true;
    return false;
  }

  static private boolean jj_3R_expression_316_21_43()
 {
    if (jj_3R_summand_330_5_53()) return true;
    return false;
  }

  static private boolean jj_3R_summand_331_5_63()
 {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_product_337_3_42()) return true;
    return false;
  }

  static private boolean jj_3R_expression_318_17_46()
 {
    if (jj_3R_summand_330_5_53()) return true;
    return false;
  }

  static private boolean jj_3R_summand_330_5_53()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_summand_330_5_62()) {
    jj_scanpos = xsp;
    if (jj_3R_summand_331_5_63()) return true;
    }
    return false;
  }

  static private boolean jj_3R_summand_330_5_62()
 {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_product_337_3_42()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_fn_call_177_5_14()) return true;
    return false;
  }

  static private boolean jj_3R_expression_317_13_45()
 {
    if (jj_3R_summand_330_5_53()) return true;
    return false;
  }

  static private boolean jj_3R_neg_324_3_44()
 {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_product_337_3_42()) return true;
    return false;
  }

  static private boolean jj_3R_expression_319_5_28()
 {
    if (jj_3R_product_337_3_42()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_expression_318_17_46()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_expression_318_5_27()
 {
    if (jj_3R_neg_324_3_44()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_expression_317_13_45()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_expression_316_5_26()
 {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_product_337_3_42()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_expression_316_21_43()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_expression_316_5_16()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_expression_316_5_26()) {
    jj_scanpos = xsp;
    if (jj_3R_expression_318_5_27()) {
    jj_scanpos = xsp;
    if (jj_3R_expression_319_5_28()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_identifier_378_5_13()) return true;
    if (jj_scan_token(ASSGN)) return true;
    return false;
  }

  static private boolean jj_3R_comparator_309_5_36()
 {
    if (jj_scan_token(NOTIN)) return true;
    return false;
  }

  static private boolean jj_3R_comparator_308_5_35()
 {
    if (jj_scan_token(IN)) return true;
    return false;
  }

  static private boolean jj_3R_comparator_307_5_34()
 {
    if (jj_scan_token(NEQ)) return true;
    return false;
  }

  static private boolean jj_3R_comparator_306_5_33()
 {
    if (jj_scan_token(EQ)) return true;
    return false;
  }

  static private boolean jj_3R_comparator_305_5_32()
 {
    if (jj_scan_token(GE)) return true;
    return false;
  }

  static private boolean jj_3R_comparator_304_5_31()
 {
    if (jj_scan_token(GREAT)) return true;
    return false;
  }

  static private boolean jj_3R_comparator_303_5_30()
 {
    if (jj_scan_token(LE)) return true;
    return false;
  }

  static private boolean jj_3R_comparator_301_5_29()
 {
    if (jj_scan_token(LESS)) return true;
    return false;
  }

  static private boolean jj_3R_comparator_301_5_17()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_comparator_301_5_29()) {
    jj_scanpos = xsp;
    if (jj_3R_comparator_303_5_30()) {
    jj_scanpos = xsp;
    if (jj_3R_comparator_304_5_31()) {
    jj_scanpos = xsp;
    if (jj_3R_comparator_305_5_32()) {
    jj_scanpos = xsp;
    if (jj_3R_comparator_306_5_33()) {
    jj_scanpos = xsp;
    if (jj_3R_comparator_307_5_34()) {
    jj_scanpos = xsp;
    if (jj_3R_comparator_308_5_35()) {
    jj_scanpos = xsp;
    if (jj_3R_comparator_309_5_36()) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_3R_expression_316_5_16()) return true;
    if (jj_3R_comparator_301_5_17()) return true;
    return false;
  }

  static private boolean jj_3R_comparison_295_3_54()
 {
    if (jj_3R_expression_316_5_16()) return true;
    if (jj_3R_comparator_301_5_17()) return true;
    if (jj_3R_expression_316_5_16()) return true;
    return false;
  }

  static private boolean jj_3R_and_clause_279_18_41()
 {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_not_clause_285_5_40()) return true;
    return false;
  }

  static private boolean jj_3R_not_clause_289_5_50()
 {
    if (jj_3R_bool_simple_386_5_55()) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_3R_boolean_call_184_3_18()) return true;
    return false;
  }

  static private boolean jj_3R_not_clause_287_5_49()
 {
    if (jj_scan_token(LRND)) return true;
    if (jj_3R_condition_273_3_15()) return true;
    if (jj_scan_token(RRND)) return true;
    return false;
  }

  static private boolean jj_3R_condition_273_18_25()
 {
    if (jj_scan_token(VBAR)) return true;
    if (jj_3R_and_clause_279_3_24()) return true;
    return false;
  }

  static private boolean jj_3R_not_clause_286_5_48()
 {
    if (jj_3R_comparison_295_3_54()) return true;
    return false;
  }

  static private boolean jj_3R_not_clause_285_5_40()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_not_clause_285_5_47()) {
    jj_scanpos = xsp;
    if (jj_3R_not_clause_286_5_48()) {
    jj_scanpos = xsp;
    if (jj_3R_not_clause_287_5_49()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3R_not_clause_289_5_50()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_not_clause_285_5_47()
 {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_not_clause_285_5_40()) return true;
    return false;
  }

  static private boolean jj_3R_and_clause_279_3_24()
 {
    if (jj_3R_not_clause_285_5_40()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_and_clause_279_18_41()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_condition_273_3_15()
 {
    if (jj_3R_and_clause_279_3_24()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_condition_273_18_25()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_number_412_3_77()
 {
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_3R_condition_273_3_15()) return true;
    return false;
  }

  static private boolean jj_3R_idbool_406_3_37()
 {
    if (jj_scan_token(IDBOOL)) return true;
    return false;
  }

  static private boolean jj_3R_vec_const_369_38_81()
 {
    if (jj_3R_exp_list_190_3_69()) return true;
    return false;
  }

  static private boolean jj_3R_condition_list_197_16_84()
 {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_condition_273_3_15()) return true;
    return false;
  }

  static private boolean jj_3R_idnum_400_3_38()
 {
    if (jj_scan_token(IDNUM)) return true;
    return false;
  }

  static private boolean jj_3R_exp_list_190_17_74()
 {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_expression_316_5_16()) return true;
    return false;
  }

  static private boolean jj_3R_idvec_394_3_39()
 {
    if (jj_scan_token(IDVEC)) return true;
    return false;
  }

  static private boolean jj_3R_bool_simple_389_5_67()
 {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  static private boolean jj_3R_bool_simple_388_5_66()
 {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  static private boolean jj_3R_boolean_call_184_17_64()
 {
    if (jj_3R_exp_list_190_3_69()) return true;
    return false;
  }

  static private boolean jj_3R_condition_list_197_3_83()
 {
    if (jj_3R_condition_273_3_15()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_condition_list_197_16_84()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_bool_simple_386_5_55()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_bool_simple_386_5_65()) {
    jj_scanpos = xsp;
    if (jj_3R_bool_simple_388_5_66()) {
    jj_scanpos = xsp;
    if (jj_3R_bool_simple_389_5_67()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_bool_simple_386_5_65()
 {
    if (jj_3R_idbool_406_3_37()) return true;
    return false;
  }

  static private boolean jj_3R_fn_call_178_18_76()
 {
    if (jj_3R_exp_list_190_3_69()) return true;
    return false;
  }

  static private boolean jj_3R_fn_call_177_18_75()
 {
    if (jj_3R_exp_list_190_3_69()) return true;
    return false;
  }

  static private boolean jj_3R_identifier_380_5_21()
 {
    if (jj_3R_idvec_394_3_39()) return true;
    return false;
  }

  static private boolean jj_3R_exp_list_190_3_69()
 {
    if (jj_3R_expression_316_5_16()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_exp_list_190_17_74()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_7()
 {
    if (jj_scan_token(LSQU)) return true;
    if (jj_3R_expression_316_5_16()) return true;
    return false;
  }

  static private boolean jj_3R_identifier_379_5_20()
 {
    if (jj_3R_idbool_406_3_37()) return true;
    return false;
  }

  static private boolean jj_3R_identifier_378_5_13()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_identifier_378_5_19()) {
    jj_scanpos = xsp;
    if (jj_3R_identifier_379_5_20()) {
    jj_scanpos = xsp;
    if (jj_3R_identifier_380_5_21()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_identifier_378_5_19()
 {
    if (jj_3R_idnum_400_3_38()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public VNMTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[44];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x80470001,0x80000000,0x470000,0x80000000,0x80000000,0x0,0x80000000,0x80000000,0x80,0x0,0x80,0x470000,0x470000,0x0,0x470000,0x80,0x80,0x470000,0x470000,0x470000,0x80,0x470000,0x0,0x0,0x20000000,0x20,0x100000,0x10000,0x10000400,0x28fa00,0x440000,0x440000,0x440000,0x470000,0x440000,0x8000100,0x10000,0x20000,0x20000,0x470000,0x10570400,0x20000,0x0,0x10000400,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x1e0ec3,0xec3,0x1e0000,0xec3,0xec3,0x1c0000,0x1c0ec3,0x1c0ec3,0x0,0x1c0000,0x0,0x160000,0x160000,0x140000,0x160000,0x0,0x0,0x160000,0x1f0000,0x1f0000,0x0,0x1f0000,0x1c0000,0x18,0x0,0x0,0x0,0x0,0x80000,0x0,0x0,0x0,0x0,0x160000,0x0,0x400000,0x0,0x160000,0x160000,0x160000,0x1e0000,0x0,0x1c0000,0x80000,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[7];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public VNM(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public VNM(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new VNMTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public VNM(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new VNMTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new VNMTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public VNM(VNMTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(VNMTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[55];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 44; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 55; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 7; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
