/* Generated By:JJTree&JavaCC: Do not edit this line. VNMConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VNMConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int ASSGN = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int DIV = 8;
  /** RegularExpression Id. */
  int EQ = 9;
  /** RegularExpression Id. */
  int FALSE = 10;
  /** RegularExpression Id. */
  int GE = 11;
  /** RegularExpression Id. */
  int GREAT = 12;
  /** RegularExpression Id. */
  int IN = 13;
  /** RegularExpression Id. */
  int LE = 14;
  /** RegularExpression Id. */
  int LESS = 15;
  /** RegularExpression Id. */
  int LRND = 16;
  /** RegularExpression Id. */
  int LSQU = 17;
  /** RegularExpression Id. */
  int MINUS = 18;
  /** RegularExpression Id. */
  int NEQ = 19;
  /** RegularExpression Id. */
  int NOT = 20;
  /** RegularExpression Id. */
  int NOTIN = 21;
  /** RegularExpression Id. */
  int PLUS = 22;
  /** RegularExpression Id. */
  int RANGE = 23;
  /** RegularExpression Id. */
  int RRND = 24;
  /** RegularExpression Id. */
  int RSQU = 25;
  /** RegularExpression Id. */
  int SCOL = 26;
  /** RegularExpression Id. */
  int TIMES = 27;
  /** RegularExpression Id. */
  int TRUE = 28;
  /** RegularExpression Id. */
  int VBAR = 29;
  /** RegularExpression Id. */
  int DO = 30;
  /** RegularExpression Id. */
  int WHILE = 31;
  /** RegularExpression Id. */
  int FOR = 32;
  /** RegularExpression Id. */
  int IF = 33;
  /** RegularExpression Id. */
  int THEN = 34;
  /** RegularExpression Id. */
  int ELIF = 35;
  /** RegularExpression Id. */
  int ELSE = 36;
  /** RegularExpression Id. */
  int FI = 37;
  /** RegularExpression Id. */
  int FUNCTION = 38;
  /** RegularExpression Id. */
  int RETURN = 39;
  /** RegularExpression Id. */
  int END = 40;
  /** RegularExpression Id. */
  int PRINT = 41;
  /** RegularExpression Id. */
  int PRINTLN = 42;
  /** RegularExpression Id. */
  int VAR = 43;
  /** RegularExpression Id. */
  int DIGIT = 44;
  /** RegularExpression Id. */
  int LOWER = 45;
  /** RegularExpression Id. */
  int UPPER = 46;
  /** RegularExpression Id. */
  int LETTER = 47;
  /** RegularExpression Id. */
  int STRING = 48;
  /** RegularExpression Id. */
  int NUMBER = 49;
  /** RegularExpression Id. */
  int IDNUM = 50;
  /** RegularExpression Id. */
  int IDBOOL = 51;
  /** RegularExpression Id. */
  int IDVEC = 52;
  /** RegularExpression Id. */
  int COMMENT_SINGLE = 53;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"&\"",
    "\":=\"",
    "\",\"",
    "\"/\"",
    "\"==\"",
    "\"#0\"",
    "\">=\"",
    "\">\"",
    "\"=in\"",
    "\"<=\"",
    "\"<\"",
    "\"(\"",
    "\"[\"",
    "\"-\"",
    "\"!=\"",
    "\"!\"",
    "\"!in\"",
    "\"+\"",
    "\"..\"",
    "\")\"",
    "\"]\"",
    "\";\"",
    "\"*\"",
    "\"#1\"",
    "\"|\"",
    "\"DO\"",
    "\"WHILE\"",
    "\"FOR\"",
    "\"IF\"",
    "\"THEN\"",
    "\"ELIF\"",
    "\"ELSE\"",
    "\"FI\"",
    "\"FUNCTION\"",
    "\"RETURN\"",
    "\"END\"",
    "\"PRINT\"",
    "\"PRINTLN\"",
    "\"VAR\"",
    "<DIGIT>",
    "<LOWER>",
    "<UPPER>",
    "<LETTER>",
    "<STRING>",
    "<NUMBER>",
    "<IDNUM>",
    "<IDBOOL>",
    "<IDVEC>",
    "<COMMENT_SINGLE>",
    "\"%\"",
  };

}
