/* Generated By:JavaCC: Do not edit this line. VNMEval.java Version 7.0.9 */
public class VNMEval implements VNMVisitor {
  public Object defaultVisit(SimpleNode node, Object data) throws Exception {
    node.childrenAccept(this, data);
    return data;
  }

  public Object visit(SimpleNode node, Object data) throws Exception {
    node.childrenAccept(this, data);
    return null;
  }

  public Object visit(ASTbody node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTclause node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTvar_decl node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTfn_decl node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTident_list node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTfn_call node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTboolean_call node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTexp_list node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTcondition_list node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTReturn node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTAssign node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTFor node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTWhile node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTin node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTnotin node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTmod node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTvec_const node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTidvec node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTidnum node, Object data) throws Exception { return defaultVisit(node, data); }
  public Object visit(ASTidbool node, Object data) throws Exception { return defaultVisit(node, data); }

  public Object visit(ASTPrint node, Object data) throws Exception {
    for (int i = 0; i < node.jjtGetNumChildren(); i++) {
      Object result = node.jjtGetChild(i).jjtAccept(this, null);
      System.out.print(result);
    }
    return null;
  }

  public Object visit(ASTPrint_ln node, Object data) throws Exception {
    for (int i = 0; i < node.jjtGetNumChildren(); i++) {
      Object result = node.jjtGetChild(i).jjtAccept(this, null);
      System.out.print(result);
    }
    System.out.println();
    return null;
  }

  public Object visit(ASTIf node, Object data) throws Exception {
    Object conditionResult = node.jjtGetChild(0).jjtAccept(this, null);
    boolean condition = false;
    if (conditionResult instanceof Boolean) {
      condition = (Boolean) conditionResult;
    }
    if (condition) {
      node.jjtGetChild(1).jjtAccept(this, null);
    } else {
      if (node.jjtGetNumChildren() > 2) {
        node.jjtGetChild(2).jjtAccept(this, null);
      }
    }
    return null;
  }

  public Object visit(ASTNULL node, Object data) throws Exception { return null; }

  public Object visit(ASTor node, Object data) throws Exception {
    for (int i = 0; i < node.jjtGetNumChildren(); i++) {
      Object result = node.jjtGetChild(i).jjtAccept(this, null);
      if (result instanceof Boolean && (Boolean) result) {
        return true;
      }
    }
    return false;
  }

  public Object visit(ASTand node, Object data) throws Exception {
    for (int i = 0; i < node.jjtGetNumChildren(); i++) {
      Object result = node.jjtGetChild(i).jjtAccept(this, null);
      if (result instanceof Boolean && !(Boolean) result) {
        return false;
      }
    }
    return true;
  }

  public Object visit(ASTnot node, Object data) throws Exception {
    Object result = node.jjtGetChild(0).jjtAccept(this, null);
    if (result instanceof Boolean) {
      return !(Boolean) result;
    }
    return false;
  }

  public Object visit(ASTcomparison node, Object data) throws Exception {
    Object left = node.jjtGetChild(0).jjtAccept(this, null);
    Object right = node.jjtGetChild(2).jjtAccept(this, null);
    SimpleNode comparator = (SimpleNode) node.jjtGetChild(1);

    int leftVal = 0, rightVal = 0;
    if (left instanceof Integer) leftVal = (Integer) left;
    if (right instanceof Integer) rightVal = (Integer) right;

    return comparator.jjtAccept(this, new int[]{leftVal, rightVal});
  }

  public Object visit(ASTle node, Object data) throws Exception { int[] vals = (int[]) data; return vals[0] < vals[1]; }
  public Object visit(ASTleq node, Object data) throws Exception { int[] vals = (int[]) data; return vals[0] <= vals[1]; }
  public Object visit(ASTgre node, Object data) throws Exception { int[] vals = (int[]) data; return vals[0] > vals[1]; }
  public Object visit(ASTgeq node, Object data) throws Exception { int[] vals = (int[]) data; return vals[0] >= vals[1]; }
  public Object visit(ASTeq node, Object data) throws Exception { int[] vals = (int[]) data; return vals[0] == vals[1]; }
  public Object visit(ASTneq node, Object data) throws Exception { int[] vals = (int[]) data; return vals[0] != vals[1]; }

  public Object visit(ASTsum node, Object data) throws Exception {
    int result = 0;
    for (int i = 0; i < node.jjtGetNumChildren(); i++) {
      Object childResult = node.jjtGetChild(i).jjtAccept(this, null);
      if (childResult instanceof Integer) {
        int value = (Integer) childResult;
        if (i == 0) result = value;
        else result += value;
      }
    }
    return result;
  }

  public Object visit(ASTneg node, Object data) throws Exception {
    Object result = node.jjtGetChild(0).jjtAccept(this, null);
    if (result instanceof Integer) return -(Integer) result;
    return 0;
  }

  public Object visit(ASTpos node, Object data) throws Exception {
    Object result = node.jjtGetChild(0).jjtAccept(this, null);
    if (result instanceof Integer) return (Integer) result;
    return 0;
  }

  public Object visit(ASTmul node, Object data) throws Exception {
    Object left = node.jjtGetChild(0).jjtAccept(this, null);
    Object right = node.jjtGetChild(1).jjtAccept(this, null);
    if (left instanceof Integer && right instanceof Integer) {
      return (Integer) left * (Integer) right;
    }
    return 0;
  }

  public Object visit(ASTdiv node, Object data) throws Exception {
    Object left = node.jjtGetChild(0).jjtAccept(this, null);
    Object right = node.jjtGetChild(1).jjtAccept(this, null);
    if (left instanceof Integer && right instanceof Integer) {
      return (Integer) left / (Integer) right;
    }
    return 0;
  }

  public Object visit(ASTTRUE node, Object data) throws Exception { return true; }
  public Object visit(ASTFALSE node, Object data) throws Exception { return false; }

  public Object visit(ASTnumber node, Object data) throws Exception {
    String value = (String) node.jjtGetValue();
    return Integer.parseInt(value);
  }

  public Object visit(ASTstring node, Object data) throws Exception {
    String value = (String) node.jjtGetValue();
    if (value.startsWith("\"") && value.endsWith("\"")) {
      value = value.substring(1, value.length() - 1);
    }
    return value;
  }
}
/* JavaCC - OriginalChecksum=22d58c5389ead436110ed9c53d7f4358 (do not edit this line) */