/* VNM.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. VNM.java */
public class VNM/*@bgen(jjtree)*/implements VNMTreeConstants, VNMConstants {/*@bgen(jjtree)*/
  protected static JJTVNMState jjtree = new JJTVNMState();

// ==================================================
//                  PARSER BEGINS
// ==================================================
  static final public 
SimpleNode start() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:
    case MINUS:
    case LRND:
    case LSQU:
    case WHILE:
    case FOR:
    case IF:
    case FUNCTION:
    case RETURN:
    case PRINT:
    case PRINTLN:
    case VAR:
    case NUMBER:
    case IDNUM:
    case IDBOOL:
    case IDVEC:{
      S();
{if ("" != null) return (SimpleNode) (jjtree.popNode());}
      break;
      }
    case 0:{
      jj_consume_token(0);
{if (true) throw new ParseException("End of File.");}
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public void S() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case WHILE:
    case FOR:
    case IF:
    case FUNCTION:
    case RETURN:
    case PRINT:
    case PRINTLN:
    case VAR:{
      statement_LL1();
      jj_consume_token(SCOL);
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      if (jj_2_1(2147483647)) {
        assign_stat();
        jj_consume_token(SCOL);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PLUS:
        case MINUS:
        case LRND:
        case LSQU:
        case NUMBER:
        case IDNUM:
        case IDVEC:{
          expression();
          jj_consume_token(SCOL);
          break;
          }
        case IDBOOL:{
          boolean_call();
          jj_consume_token(SCOL);
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}

// Helper productions marked #void to simplify the tree
  static final public void statement_LL1() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VAR:{
      var_decl();
      break;
      }
    case FUNCTION:{
      fn_decl();
      break;
      }
    case RETURN:{
      return_stat();
      break;
      }
    case PRINT:{
      print_stat();
      break;
      }
    case PRINTLN:{
      println_stat();
      break;
      }
    case IF:{
      if_stat();
      break;
      }
    case FOR:{
      for_stat();
      break;
      }
    case WHILE:{
      while_stat();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void statement() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case WHILE:
    case FOR:
    case IF:
    case FUNCTION:
    case RETURN:
    case PRINT:
    case PRINTLN:
    case VAR:{
      statement_LL1();
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      if (jj_2_2(2)) {
        fn_call();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDNUM:
        case IDBOOL:
        case IDVEC:{
          assign_stat();
          break;
          }
        default:
          jj_la1[5] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}

  static final public void body() throws ParseException {/*@bgen(jjtree) body */
  ASTbody jjtn000 = new ASTbody(JJTBODY);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case WHILE:
        case FOR:
        case IF:
        case FUNCTION:
        case RETURN:
        case PRINT:
        case PRINTLN:
        case VAR:
        case IDNUM:
        case IDBOOL:
        case IDVEC:{
          ;
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          break label_1;
        }
        statement();
        jj_consume_token(SCOL);
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void clause() throws ParseException {/*@bgen(jjtree) clause */
  ASTclause jjtn000 = new ASTclause(JJTCLAUSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      label_2:
      while (true) {
        statement();
        jj_consume_token(SCOL);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case WHILE:
        case FOR:
        case IF:
        case FUNCTION:
        case RETURN:
        case PRINT:
        case PRINTLN:
        case VAR:
        case IDNUM:
        case IDBOOL:
        case IDVEC:{
          ;
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          break label_2;
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

//--------------------------- DECLARATIONS ------------------------------------------------

// AST: Flattens the list so identifiers are direct children of var_decl
  static final public void var_decl() throws ParseException {/*@bgen(jjtree) var_decl */
  ASTvar_decl jjtn000 = new ASTvar_decl(JJTVAR_DECL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(VAR);
      identifier();
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_3;
        }
        jj_consume_token(COMMA);
        identifier();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

// AST: Calls ident_list to create a nested node for functions
  static final public void fn_decl() throws ParseException {/*@bgen(jjtree) fn_decl */
  ASTfn_decl jjtn000 = new ASTfn_decl(JJTFN_DECL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FUNCTION);
      identifier();
      jj_consume_token(LRND);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDNUM:
      case IDBOOL:
      case IDVEC:{
        ident_list();
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        ;
      }
      jj_consume_token(RRND);
      body();
      jj_consume_token(END);
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

// AST: Explicit node for function parameter lists
  static final public void ident_list() throws ParseException {/*@bgen(jjtree) ident_list */
  ASTident_list jjtn000 = new ASTident_list(JJTIDENT_LIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      identifier();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          break label_4;
        }
        jj_consume_token(COMMA);
        identifier();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

//--------------------------- FUNCTION CALLS AND RETURNS ----------------------------------
  static final public 
void fn_call() throws ParseException {/*@bgen(jjtree) fn_call */
  ASTfn_call jjtn000 = new ASTfn_call(JJTFN_CALL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDNUM:{
        jj_consume_token(IDNUM);
ASTidnum jjtn001 = new ASTidnum(JJTIDNUM);
            boolean jjtc001 = true;
            jjtree.openNodeScope(jjtn001);
        try {
jjtree.closeNodeScope(jjtn001, true);
            jjtc001 = false;
jjtn001.jjtSetValue(token.image);
        } finally {
if (jjtc001) {
              jjtree.closeNodeScope(jjtn001, true);
            }
        }
        jj_consume_token(LRND);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PLUS:
        case MINUS:
        case LRND:
        case LSQU:
        case NUMBER:
        case IDNUM:
        case IDVEC:{
          exp_list();
          break;
          }
        default:
          jj_la1[11] = jj_gen;
          ;
        }
        jj_consume_token(RRND);
        break;
        }
      case IDVEC:{
        jj_consume_token(IDVEC);
ASTidvec jjtn002 = new ASTidvec(JJTIDVEC);
            boolean jjtc002 = true;
            jjtree.openNodeScope(jjtn002);
        try {
jjtree.closeNodeScope(jjtn002, true);
            jjtc002 = false;
jjtn002.jjtSetValue(token.image);
        } finally {
if (jjtc002) {
              jjtree.closeNodeScope(jjtn002, true);
            }
        }
        jj_consume_token(LRND);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PLUS:
        case MINUS:
        case LRND:
        case LSQU:
        case NUMBER:
        case IDNUM:
        case IDVEC:{
          exp_list();
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          ;
        }
        jj_consume_token(RRND);
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void boolean_call() throws ParseException {/*@bgen(jjtree) boolean_call */
  ASTboolean_call jjtn000 = new ASTboolean_call(JJTBOOLEAN_CALL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(IDBOOL);
ASTidbool jjtn001 = new ASTidbool(JJTIDBOOL);
             boolean jjtc001 = true;
             jjtree.openNodeScope(jjtn001);
      try {
jjtree.closeNodeScope(jjtn001, true);
             jjtc001 = false;
jjtn001.jjtSetValue(token.image);
      } finally {
if (jjtc001) {
               jjtree.closeNodeScope(jjtn001, true);
             }
      }
      jj_consume_token(LRND);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:
      case LRND:
      case LSQU:
      case NUMBER:
      case IDNUM:
      case IDVEC:{
        exp_list();
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        ;
      }
      jj_consume_token(RRND);
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void exp_list() throws ParseException {/*@bgen(jjtree) exp_list */
  ASTexp_list jjtn000 = new ASTexp_list(JJTEXP_LIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      expression();
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[15] = jj_gen;
          break label_5;
        }
        jj_consume_token(COMMA);
        expression();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void condition_list() throws ParseException {/*@bgen(jjtree) condition_list */
  ASTcondition_list jjtn000 = new ASTcondition_list(JJTCONDITION_LIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      condition();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[16] = jj_gen;
          break label_6;
        }
        jj_consume_token(COMMA);
        condition();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void return_stat() throws ParseException {/*@bgen(jjtree) Return */
  ASTReturn jjtn000 = new ASTReturn(JJTRETURN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(RETURN);
      returnval();
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void returnval() throws ParseException {
    if (jj_2_3(2147483647)) {
      condition();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:
      case LRND:
      case LSQU:
      case NUMBER:
      case IDNUM:
      case IDVEC:{
        expression();
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  static final public void print_stat() throws ParseException {/*@bgen(jjtree) Print */
  ASTPrint jjtn000 = new ASTPrint(JJTPRINT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(PRINT);
      print_list();
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void println_stat() throws ParseException {/*@bgen(jjtree) Print_ln */
  ASTPrint_ln jjtn000 = new ASTPrint_ln(JJTPRINT_LN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(PRINTLN);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:
      case LRND:
      case LSQU:
      case STRING:
      case NUMBER:
      case IDNUM:
      case IDBOOL:
      case IDVEC:{
        print_list();
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void print_list() throws ParseException {
    printable();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        break label_7;
      }
      jj_consume_token(COMMA);
      printable();
    }
}

  static final public void printable() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:
    case MINUS:
    case LRND:
    case LSQU:
    case NUMBER:
    case IDNUM:
    case IDVEC:{
      expression();
      break;
      }
    case STRING:{
      jj_consume_token(STRING);
ASTstring jjtn001 = new ASTstring(JJTSTRING);
             boolean jjtc001 = true;
             jjtree.openNodeScope(jjtn001);
      try {
jjtree.closeNodeScope(jjtn001, true);
             jjtc001 = false;
// Strip quotes from string before storing
      jjtn001.jjtSetValue(token.image.substring(1, token.image.length()-1));
      } finally {
if (jjtc001) {
               jjtree.closeNodeScope(jjtn001, true);
             }
      }
      break;
      }
    case IDBOOL:{
      jj_consume_token(IDBOOL);
ASTidbool jjtn002 = new ASTidbool(JJTIDBOOL);
             boolean jjtc002 = true;
             jjtree.openNodeScope(jjtn002);
      try {
jjtree.closeNodeScope(jjtn002, true);
             jjtc002 = false;
jjtn002.jjtSetValue(token.image);
      } finally {
if (jjtc002) {
               jjtree.closeNodeScope(jjtn002, true);
             }
      }
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void assign_stat() throws ParseException {/*@bgen(jjtree) Assign */
  ASTAssign jjtn000 = new ASTAssign(JJTASSIGN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDNUM:{
        jj_consume_token(IDNUM);
ASTidnum jjtn001 = new ASTidnum(JJTIDNUM);
            boolean jjtc001 = true;
            jjtree.openNodeScope(jjtn001);
        try {
jjtree.closeNodeScope(jjtn001, true);
            jjtc001 = false;
jjtn001.jjtSetValue(token.image);
        } finally {
if (jjtc001) {
              jjtree.closeNodeScope(jjtn001, true);
            }
        }
        jj_consume_token(ASSGN);
        expression();
        break;
        }
      case IDBOOL:{
        jj_consume_token(IDBOOL);
ASTidbool jjtn002 = new ASTidbool(JJTIDBOOL);
             boolean jjtc002 = true;
             jjtree.openNodeScope(jjtn002);
        try {
jjtree.closeNodeScope(jjtn002, true);
             jjtc002 = false;
jjtn002.jjtSetValue(token.image);
        } finally {
if (jjtc002) {
               jjtree.closeNodeScope(jjtn002, true);
             }
        }
        jj_consume_token(ASSGN);
        condition();
        break;
        }
      case IDVEC:{
        jj_consume_token(IDVEC);
ASTidvec jjtn003 = new ASTidvec(JJTIDVEC);
            boolean jjtc003 = true;
            jjtree.openNodeScope(jjtn003);
        try {
jjtree.closeNodeScope(jjtn003, true);
            jjtc003 = false;
jjtn003.jjtSetValue(token.image);
        } finally {
if (jjtc003) {
              jjtree.closeNodeScope(jjtn003, true);
            }
        }
        jj_consume_token(ASSGN);
        vec_const();
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void if_stat() throws ParseException {/*@bgen(jjtree) If */
  ASTIf jjtn000 = new ASTIf(JJTIF);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(IF);
      condition();
      jj_consume_token(THEN);
      clause();
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ELIF:
        case ELSE:
        case FI:{
          ;
          break;
          }
        default:
          jj_la1[22] = jj_gen;
          break label_8;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ELSE:{
          jj_consume_token(ELSE);
          clause();
          jj_consume_token(FI);
          break;
          }
        case FI:{
ASTNULL jjtn001 = new ASTNULL(JJTNULL);
      boolean jjtc001 = true;
      jjtree.openNodeScope(jjtn001);
          try {
            jj_consume_token(FI);
          } finally {
if (jjtc001) {
        jjtree.closeNodeScope(jjtn001, true);
      }
          }
          break;
          }
        case ELIF:{
          if_recursion();
          break;
          }
        default:
          jj_la1[23] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void if_recursion() throws ParseException {/*@bgen(jjtree) If */
  ASTIf jjtn000 = new ASTIf(JJTIF);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(ELIF);
      condition();
      jj_consume_token(THEN);
      clause();
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void for_stat() throws ParseException {/*@bgen(jjtree) For */
  ASTFor jjtn000 = new ASTFor(JJTFOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(FOR);
      jj_consume_token(IDNUM);
ASTidnum jjtn001 = new ASTidnum(JJTIDNUM);
                  boolean jjtc001 = true;
                  jjtree.openNodeScope(jjtn001);
      try {
jjtree.closeNodeScope(jjtn001, true);
                  jjtc001 = false;
jjtn001.jjtSetValue(token.image);
      } finally {
if (jjtc001) {
                    jjtree.closeNodeScope(jjtn001, true);
                  }
      }
      jj_consume_token(IN);
      exp_list();
      jj_consume_token(DO);
      body();
      jj_consume_token(END);
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void while_stat() throws ParseException {/*@bgen(jjtree) While */
  ASTWhile jjtn000 = new ASTWhile(JJTWHILE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(WHILE);
      condition();
      jj_consume_token(DO);
      body();
      jj_consume_token(END);
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

//--------------------------- CONDITIONS ---------------------------------------------------
  static final public 
void condition() throws ParseException {
ASTor jjtn001 = new ASTor(JJTOR);
    boolean jjtc001 = true;
    jjtree.openNodeScope(jjtn001);
    try {
      and_clause();
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case VBAR:{
          ;
          break;
          }
        default:
          jj_la1[24] = jj_gen;
          break label_9;
        }
        jj_consume_token(VBAR);
        and_clause();
      }
    } catch (Throwable jjte001) {
if (jjtc001) {
      jjtree.clearNodeScope(jjtn001);
      jjtc001 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte001 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte001;}
    }
    if (jjte001 instanceof ParseException) {
      {if (true) throw (ParseException)jjte001;}
    }
    {if (true) throw (Error)jjte001;}
    } finally {
if (jjtc001) {
      jjtree.closeNodeScope(jjtn001, jjtree.nodeArity() > 1);
    }
    }
}

  static final public void and_clause() throws ParseException {
ASTand jjtn001 = new ASTand(JJTAND);
    boolean jjtc001 = true;
    jjtree.openNodeScope(jjtn001);
    try {
      not_clause();
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case AND:{
          ;
          break;
          }
        default:
          jj_la1[25] = jj_gen;
          break label_10;
        }
        jj_consume_token(AND);
        not_clause();
      }
    } catch (Throwable jjte001) {
if (jjtc001) {
      jjtree.clearNodeScope(jjtn001);
      jjtc001 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte001 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte001;}
    }
    if (jjte001 instanceof ParseException) {
      {if (true) throw (ParseException)jjte001;}
    }
    {if (true) throw (Error)jjte001;}
    } finally {
if (jjtc001) {
      jjtree.closeNodeScope(jjtn001, jjtree.nodeArity() > 1);
    }
    }
}

  static final public void not_clause() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NOT:{
      jj_consume_token(NOT);
ASTnot jjtn001 = new ASTnot(JJTNOT);
        boolean jjtc001 = true;
        jjtree.openNodeScope(jjtn001);
      try {
        not_clause();
      } catch (Throwable jjte001) {
if (jjtc001) {
          jjtree.clearNodeScope(jjtn001);
          jjtc001 = false;
        } else {
          jjtree.popNode();
        }
        if (jjte001 instanceof RuntimeException) {
          {if (true) throw (RuntimeException)jjte001;}
        }
        if (jjte001 instanceof ParseException) {
          {if (true) throw (ParseException)jjte001;}
        }
        {if (true) throw (Error)jjte001;}
      } finally {
if (jjtc001) {
          jjtree.closeNodeScope(jjtn001, true);
        }
      }
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      if (jj_2_4(2147483647)) {
        comparison();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LRND:{
          jj_consume_token(LRND);
          condition();
          jj_consume_token(RRND);
          break;
          }
        default:
          jj_la1[27] = jj_gen;
          if (jj_2_5(2)) {
            boolean_call();
          } else {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case TRUE:
            case FALSE:
            case IDBOOL:{
              bool_simple();
              break;
              }
            default:
              jj_la1[28] = jj_gen;
              jj_consume_token(-1);
              throw new ParseException();
            }
          }
        }
      }
    }
}

  static final public void comparison() throws ParseException {/*@bgen(jjtree) comparison */
  ASTcomparison jjtn000 = new ASTcomparison(JJTCOMPARISON);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      expression();
      comparator();
      expression();
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

// AST: Node-ify comparator tokens
  static final public void comparator() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LESS:{
ASTle jjtn001 = new ASTle(JJTLE);
    boolean jjtc001 = true;
    jjtree.openNodeScope(jjtn001);
      try {
        jj_consume_token(LESS);
      } finally {
if (jjtc001) {
      jjtree.closeNodeScope(jjtn001, true);
    }
      }
      break;
      }
    case LE:{
ASTleq jjtn002 = new ASTleq(JJTLEQ);
              boolean jjtc002 = true;
              jjtree.openNodeScope(jjtn002);
      try {
        jj_consume_token(LE);
      } finally {
if (jjtc002) {
                jjtree.closeNodeScope(jjtn002, true);
              }
      }
      break;
      }
    case GREAT:{
ASTgre jjtn003 = new ASTgre(JJTGRE);
                          boolean jjtc003 = true;
                          jjtree.openNodeScope(jjtn003);
      try {
        jj_consume_token(GREAT);
      } finally {
if (jjtc003) {
                            jjtree.closeNodeScope(jjtn003, true);
                          }
      }
      break;
      }
    case GE:{
ASTgeq jjtn004 = new ASTgeq(JJTGEQ);
                                     boolean jjtc004 = true;
                                     jjtree.openNodeScope(jjtn004);
      try {
        jj_consume_token(GE);
      } finally {
if (jjtc004) {
                                       jjtree.closeNodeScope(jjtn004, true);
                                     }
      }
      break;
      }
    case EQ:{
ASTeq jjtn005 = new ASTeq(JJTEQ);
    boolean jjtc005 = true;
    jjtree.openNodeScope(jjtn005);
      try {
        jj_consume_token(EQ);
      } finally {
if (jjtc005) {
      jjtree.closeNodeScope(jjtn005, true);
    }
      }
      break;
      }
    case NEQ:{
ASTneq jjtn006 = new ASTneq(JJTNEQ);
               boolean jjtc006 = true;
               jjtree.openNodeScope(jjtn006);
      try {
        jj_consume_token(NEQ);
      } finally {
if (jjtc006) {
                 jjtree.closeNodeScope(jjtn006, true);
               }
      }
      break;
      }
    case IN:{
ASTin jjtn007 = new ASTin(JJTIN);
                           boolean jjtc007 = true;
                           jjtree.openNodeScope(jjtn007);
      try {
        jj_consume_token(IN);
      } finally {
if (jjtc007) {
                             jjtree.closeNodeScope(jjtn007, true);
                           }
      }
      break;
      }
    case NOTIN:{
ASTnotin jjtn008 = new ASTnotin(JJTNOTIN);
                                       boolean jjtc008 = true;
                                       jjtree.openNodeScope(jjtn008);
      try {
        jj_consume_token(NOTIN);
      } finally {
if (jjtc008) {
                                         jjtree.closeNodeScope(jjtn008, true);
                                       }
      }
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

//--------------------------- EXPRESSIONS ------------------------------------------------
  static final public 
void expression() throws ParseException {
    sum();
}

// AST: N-ary sum node where children are tagged #pos or #neg
  static final public void sum() throws ParseException {
    if (jj_2_6(2)) {
ASTsum jjtn002 = new ASTsum(JJTSUM);
                   boolean jjtc002 = true;
                   jjtree.openNodeScope(jjtn002);
      try {
ASTneg jjtn001 = new ASTneg(JJTNEG);
                     boolean jjtc001 = true;
                     jjtree.openNodeScope(jjtn001);
        try {
          jj_consume_token(MINUS);
        } finally {
if (jjtc001) {
                       jjtree.closeNodeScope(jjtn001, true);
                     }
        }
        product();
        label_11:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case PLUS:
          case MINUS:{
            ;
            break;
            }
          default:
            jj_la1[30] = jj_gen;
            break label_11;
          }
          add_sub_term();
        }
      } catch (Throwable jjte002) {
if (jjtc002) {
                     jjtree.clearNodeScope(jjtn002);
                     jjtc002 = false;
                   } else {
                     jjtree.popNode();
                   }
                   if (jjte002 instanceof RuntimeException) {
                     {if (true) throw (RuntimeException)jjte002;}
                   }
                   if (jjte002 instanceof ParseException) {
                     {if (true) throw (ParseException)jjte002;}
                   }
                   {if (true) throw (Error)jjte002;}
      } finally {
if (jjtc002) {
                     jjtree.closeNodeScope(jjtn002, true);
                   }
      }
    } else if (jj_2_7(2)) {
ASTsum jjtn003 = new ASTsum(JJTSUM);
                   boolean jjtc003 = true;
                   jjtree.openNodeScope(jjtn003);
      try {
        jj_consume_token(PLUS);
        product();
        label_12:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case PLUS:
          case MINUS:{
            ;
            break;
            }
          default:
            jj_la1[31] = jj_gen;
            break label_12;
          }
          add_sub_term();
        }
      } catch (Throwable jjte003) {
if (jjtc003) {
                     jjtree.clearNodeScope(jjtn003);
                     jjtc003 = false;
                   } else {
                     jjtree.popNode();
                   }
                   if (jjte003 instanceof RuntimeException) {
                     {if (true) throw (RuntimeException)jjte003;}
                   }
                   if (jjte003 instanceof ParseException) {
                     {if (true) throw (ParseException)jjte003;}
                   }
                   {if (true) throw (Error)jjte003;}
      } finally {
if (jjtc003) {
                     jjtree.closeNodeScope(jjtn003, jjtree.nodeArity() > 1);
                   }
      }
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:
      case LRND:
      case LSQU:
      case NUMBER:
      case IDNUM:
      case IDVEC:{
ASTsum jjtn004 = new ASTsum(JJTSUM);
      boolean jjtc004 = true;
      jjtree.openNodeScope(jjtn004);
        try {
          product();
          label_13:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case PLUS:
            case MINUS:{
              ;
              break;
              }
            default:
              jj_la1[32] = jj_gen;
              break label_13;
            }
            add_sub_term();
          }
        } catch (Throwable jjte004) {
if (jjtc004) {
        jjtree.clearNodeScope(jjtn004);
        jjtc004 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte004 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte004;}
      }
      if (jjte004 instanceof ParseException) {
        {if (true) throw (ParseException)jjte004;}
      }
      {if (true) throw (Error)jjte004;}
        } finally {
if (jjtc004) {
        jjtree.closeNodeScope(jjtn004, jjtree.nodeArity() > 1);
      }
        }
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  static final public void add_sub_term() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:{
      jj_consume_token(PLUS);
ASTpos jjtn001 = new ASTpos(JJTPOS);
            boolean jjtc001 = true;
            jjtree.openNodeScope(jjtn001);
      try {
        product();
      } catch (Throwable jjte001) {
if (jjtc001) {
              jjtree.clearNodeScope(jjtn001);
              jjtc001 = false;
            } else {
              jjtree.popNode();
            }
            if (jjte001 instanceof RuntimeException) {
              {if (true) throw (RuntimeException)jjte001;}
            }
            if (jjte001 instanceof ParseException) {
              {if (true) throw (ParseException)jjte001;}
            }
            {if (true) throw (Error)jjte001;}
      } finally {
if (jjtc001) {
              jjtree.closeNodeScope(jjtn001, true);
            }
      }
      break;
      }
    case MINUS:{
      jj_consume_token(MINUS);
ASTneg jjtn002 = new ASTneg(JJTNEG);
            boolean jjtc002 = true;
            jjtree.openNodeScope(jjtn002);
      try {
        product();
      } catch (Throwable jjte002) {
if (jjtc002) {
              jjtree.clearNodeScope(jjtn002);
              jjtc002 = false;
            } else {
              jjtree.popNode();
            }
            if (jjte002 instanceof RuntimeException) {
              {if (true) throw (RuntimeException)jjte002;}
            }
            if (jjte002 instanceof ParseException) {
              {if (true) throw (ParseException)jjte002;}
            }
            {if (true) throw (Error)jjte002;}
      } finally {
if (jjtc002) {
              jjtree.closeNodeScope(jjtn002, true);
            }
      }
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void product() throws ParseException {
    unary();
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIMES:
      case DIV:
      case MOD:{
        ;
        break;
        }
      default:
        jj_la1[35] = jj_gen;
        break label_14;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIMES:{
        jj_consume_token(TIMES);
ASTmul jjtn001 = new ASTmul(JJTMUL);
              boolean jjtc001 = true;
              jjtree.openNodeScope(jjtn001);
        try {
          unary();
        } catch (Throwable jjte001) {
if (jjtc001) {
                jjtree.clearNodeScope(jjtn001);
                jjtc001 = false;
              } else {
                jjtree.popNode();
              }
              if (jjte001 instanceof RuntimeException) {
                {if (true) throw (RuntimeException)jjte001;}
              }
              if (jjte001 instanceof ParseException) {
                {if (true) throw (ParseException)jjte001;}
              }
              {if (true) throw (Error)jjte001;}
        } finally {
if (jjtc001) {
                jjtree.closeNodeScope(jjtn001,  2);
              }
        }
        break;
        }
      case DIV:{
        jj_consume_token(DIV);
ASTdiv jjtn002 = new ASTdiv(JJTDIV);
              boolean jjtc002 = true;
              jjtree.openNodeScope(jjtn002);
        try {
          unary();
        } catch (Throwable jjte002) {
if (jjtc002) {
                jjtree.clearNodeScope(jjtn002);
                jjtc002 = false;
              } else {
                jjtree.popNode();
              }
              if (jjte002 instanceof RuntimeException) {
                {if (true) throw (RuntimeException)jjte002;}
              }
              if (jjte002 instanceof ParseException) {
                {if (true) throw (ParseException)jjte002;}
              }
              {if (true) throw (Error)jjte002;}
        } finally {
if (jjtc002) {
                jjtree.closeNodeScope(jjtn002,  2);
              }
        }
        break;
        }
      case MOD:{
        jj_consume_token(MOD);
ASTmod jjtn003 = new ASTmod(JJTMOD);
              boolean jjtc003 = true;
              jjtree.openNodeScope(jjtn003);
        try {
          unary();
        } catch (Throwable jjte003) {
if (jjtc003) {
                jjtree.clearNodeScope(jjtn003);
                jjtc003 = false;
              } else {
                jjtree.popNode();
              }
              if (jjte003 instanceof RuntimeException) {
                {if (true) throw (RuntimeException)jjte003;}
              }
              if (jjte003 instanceof ParseException) {
                {if (true) throw (ParseException)jjte003;}
              }
              {if (true) throw (Error)jjte003;}
        } finally {
if (jjtc003) {
                jjtree.closeNodeScope(jjtn003,  2);
              }
        }
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
}

  static final public void unary() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MINUS:{
      jj_consume_token(MINUS);
ASTneg jjtn001 = new ASTneg(JJTNEG);
            boolean jjtc001 = true;
            jjtree.openNodeScope(jjtn001);
      try {
        unary();
      } catch (Throwable jjte001) {
if (jjtc001) {
              jjtree.clearNodeScope(jjtn001);
              jjtc001 = false;
            } else {
              jjtree.popNode();
            }
            if (jjte001 instanceof RuntimeException) {
              {if (true) throw (RuntimeException)jjte001;}
            }
            if (jjte001 instanceof ParseException) {
              {if (true) throw (ParseException)jjte001;}
            }
            {if (true) throw (Error)jjte001;}
      } finally {
if (jjtc001) {
              jjtree.closeNodeScope(jjtn001, true);
            }
      }
      break;
      }
    case PLUS:{
      jj_consume_token(PLUS);
ASTpos jjtn002 = new ASTpos(JJTPOS);
            boolean jjtc002 = true;
            jjtree.openNodeScope(jjtn002);
      try {
        unary();
      } catch (Throwable jjte002) {
if (jjtc002) {
              jjtree.clearNodeScope(jjtn002);
              jjtc002 = false;
            } else {
              jjtree.popNode();
            }
            if (jjte002 instanceof RuntimeException) {
              {if (true) throw (RuntimeException)jjte002;}
            }
            if (jjte002 instanceof ParseException) {
              {if (true) throw (ParseException)jjte002;}
            }
            {if (true) throw (Error)jjte002;}
      } finally {
if (jjtc002) {
              jjtree.closeNodeScope(jjtn002, true);
            }
      }
      break;
      }
    case LRND:
    case LSQU:
    case NUMBER:
    case IDNUM:
    case IDVEC:{
      term();
      break;
      }
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void term() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LRND:{
      jj_consume_token(LRND);
      expression();
      jj_consume_token(RRND);
      break;
      }
    default:
      jj_la1[38] = jj_gen;
      if (jj_2_8(2)) {
        fn_call();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LSQU:
        case NUMBER:
        case IDNUM:
        case IDVEC:{
          simple_term();
          break;
          }
        default:
          jj_la1[39] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
}

  static final public void simple_term() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDNUM:{
      jj_consume_token(IDNUM);
ASTidnum jjtn001 = new ASTidnum(JJTIDNUM);
            boolean jjtc001 = true;
            jjtree.openNodeScope(jjtn001);
      try {
jjtree.closeNodeScope(jjtn001, true);
            jjtc001 = false;
jjtn001.jjtSetValue(token.image);
      } finally {
if (jjtc001) {
              jjtree.closeNodeScope(jjtn001, true);
            }
      }
      break;
      }
    case IDVEC:{
      jj_consume_token(IDVEC);
ASTidvec jjtn002 = new ASTidvec(JJTIDVEC);
            boolean jjtc002 = true;
            jjtree.openNodeScope(jjtn002);
      try {
jjtree.closeNodeScope(jjtn002, true);
            jjtc002 = false;
jjtn002.jjtSetValue(token.image);
      } finally {
if (jjtc002) {
              jjtree.closeNodeScope(jjtn002, true);
            }
      }
      break;
      }
    case NUMBER:{
      jj_consume_token(NUMBER);
ASTnumber jjtn003 = new ASTnumber(JJTNUMBER);
             boolean jjtc003 = true;
             jjtree.openNodeScope(jjtn003);
      try {
jjtree.closeNodeScope(jjtn003, true);
             jjtc003 = false;
jjtn003.jjtSetValue(token.image);
      } finally {
if (jjtc003) {
               jjtree.closeNodeScope(jjtn003, true);
             }
      }
      break;
      }
    case LSQU:{
      vec_const();
      break;
      }
    default:
      jj_la1[40] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void vec_const() throws ParseException {/*@bgen(jjtree) vec_const */
  ASTvec_const jjtn000 = new ASTvec_const(JJTVEC_CONST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      if (jj_2_9(2147483647)) {
        jj_consume_token(LSQU);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PLUS:
        case MINUS:
        case LRND:
        case LSQU:
        case NUMBER:
        case IDNUM:
        case IDVEC:{
          exp_list();
          break;
          }
        default:
          jj_la1[41] = jj_gen;
          ;
        }
        jj_consume_token(RSQU);
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LSQU:{
          jj_consume_token(LSQU);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case PLUS:
          case MINUS:
          case NOT:
          case LRND:
          case LSQU:
          case TRUE:
          case FALSE:
          case NUMBER:
          case IDNUM:
          case IDBOOL:
          case IDVEC:{
            condition_list();
            break;
            }
          default:
            jj_la1[42] = jj_gen;
            ;
          }
          jj_consume_token(RSQU);
          break;
          }
        default:
          jj_la1[43] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
}

  static final public void identifier() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDNUM:{
      jj_consume_token(IDNUM);
ASTidnum jjtn001 = new ASTidnum(JJTIDNUM);
            boolean jjtc001 = true;
            jjtree.openNodeScope(jjtn001);
      try {
jjtree.closeNodeScope(jjtn001, true);
            jjtc001 = false;
jjtn001.jjtSetValue(token.image);
      } finally {
if (jjtc001) {
              jjtree.closeNodeScope(jjtn001, true);
            }
      }
      break;
      }
    case IDBOOL:{
      jj_consume_token(IDBOOL);
ASTidbool jjtn002 = new ASTidbool(JJTIDBOOL);
             boolean jjtc002 = true;
             jjtree.openNodeScope(jjtn002);
      try {
jjtree.closeNodeScope(jjtn002, true);
             jjtc002 = false;
jjtn002.jjtSetValue(token.image);
      } finally {
if (jjtc002) {
               jjtree.closeNodeScope(jjtn002, true);
             }
      }
      break;
      }
    case IDVEC:{
      jj_consume_token(IDVEC);
ASTidvec jjtn003 = new ASTidvec(JJTIDVEC);
            boolean jjtc003 = true;
            jjtree.openNodeScope(jjtn003);
      try {
jjtree.closeNodeScope(jjtn003, true);
            jjtc003 = false;
jjtn003.jjtSetValue(token.image);
      } finally {
if (jjtc003) {
              jjtree.closeNodeScope(jjtn003, true);
            }
      }
      break;
      }
    default:
      jj_la1[44] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void bool_simple() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDBOOL:{
      jj_consume_token(IDBOOL);
ASTidbool jjtn001 = new ASTidbool(JJTIDBOOL);
             boolean jjtc001 = true;
             jjtree.openNodeScope(jjtn001);
      try {
jjtree.closeNodeScope(jjtn001, true);
             jjtc001 = false;
jjtn001.jjtSetValue(token.image);
      } finally {
if (jjtc001) {
               jjtree.closeNodeScope(jjtn001, true);
             }
      }
      break;
      }
    case TRUE:{
ASTTRUE jjtn002 = new ASTTRUE(JJTTRUE);
    boolean jjtc002 = true;
    jjtree.openNodeScope(jjtn002);
      try {
        jj_consume_token(TRUE);
      } finally {
if (jjtc002) {
      jjtree.closeNodeScope(jjtn002, true);
    }
      }
      break;
      }
    case FALSE:{
ASTFALSE jjtn003 = new ASTFALSE(JJTFALSE);
    boolean jjtc003 = true;
    jjtree.openNodeScope(jjtn003);
      try {
        jj_consume_token(FALSE);
      } finally {
if (jjtc003) {
      jjtree.closeNodeScope(jjtn003, true);
    }
      }
      break;
      }
    default:
      jj_la1[45] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_9()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_3R_fn_call_129_61_78()
 {
    if (jj_3R_exp_list_142_3_69()) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_3R_condition_217_3_17()) return true;
    return false;
  }

  static private boolean jj_3R_condition_list_145_16_83()
 {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_condition_217_3_17()) return true;
    return false;
  }

  static private boolean jj_3R_exp_list_141_17_74()
 {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_expression_249_3_18()) return true;
    return false;
  }

  static private boolean jj_3R_vec_const_306_36_80()
 {
    if (jj_3R_exp_list_142_3_69()) return true;
    return false;
  }

  static private boolean jj_3R_condition_list_146_3_82()
 {
    if (jj_3R_condition_217_3_17()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_condition_list_145_16_83()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_exp_list_142_3_69()
 {
    if (jj_3R_expression_249_3_18()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_exp_list_141_17_74()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_boolean_call_136_3_20()
 {
    if (jj_scan_token(IDBOOL)) return true;
    if (jj_scan_token(LRND)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_boolean_call_136_63_59()) jj_scanpos = xsp;
    if (jj_scan_token(RRND)) return true;
    return false;
  }

  static private boolean jj_3R_bool_simple_324_3_62()
 {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  static private boolean jj_3R_bool_simple_323_3_61()
 {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  static private boolean jj_3R_fn_call_130_3_26()
 {
    if (jj_scan_token(IDVEC)) return true;
    if (jj_scan_token(LRND)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_fn_call_130_61_79()) jj_scanpos = xsp;
    if (jj_scan_token(RRND)) return true;
    return false;
  }

  static private boolean jj_3R_bool_simple_321_3_54()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_bool_simple_321_3_60()) {
    jj_scanpos = xsp;
    if (jj_3R_bool_simple_323_3_61()) {
    jj_scanpos = xsp;
    if (jj_3R_bool_simple_324_3_62()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_bool_simple_321_3_60()
 {
    if (jj_scan_token(IDBOOL)) return true;
    return false;
  }

  static private boolean jj_3R_fn_call_129_3_25()
 {
    if (jj_scan_token(IDNUM)) return true;
    if (jj_scan_token(LRND)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_fn_call_129_61_78()) jj_scanpos = xsp;
    if (jj_scan_token(RRND)) return true;
    return false;
  }

  static private boolean jj_3R_fn_call_128_3_16()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_fn_call_129_3_25()) {
    jj_scanpos = xsp;
    if (jj_3R_fn_call_130_3_26()) return true;
    }
    return false;
  }

  static private boolean jj_3_9()
 {
    if (jj_scan_token(LSQU)) return true;
    if (jj_3R_expression_249_3_18()) return true;
    return false;
  }

  static private boolean jj_3R_identifier_315_3_24()
 {
    if (jj_scan_token(IDVEC)) return true;
    return false;
  }

  static private boolean jj_3R_identifier_314_3_23()
 {
    if (jj_scan_token(IDBOOL)) return true;
    return false;
  }

  static private boolean jj_3R_identifier_313_3_15()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_identifier_313_3_22()) {
    jj_scanpos = xsp;
    if (jj_3R_identifier_314_3_23()) {
    jj_scanpos = xsp;
    if (jj_3R_identifier_315_3_24()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_identifier_313_3_22()
 {
    if (jj_scan_token(IDNUM)) return true;
    return false;
  }

  static private boolean jj_3R_vec_const_307_8_81()
 {
    if (jj_3R_condition_list_146_3_82()) return true;
    return false;
  }

  static private boolean jj_3R_vec_const_307_3_77()
 {
    if (jj_scan_token(LSQU)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_vec_const_307_8_81()) jj_scanpos = xsp;
    if (jj_scan_token(RSQU)) return true;
    return false;
  }

  static private boolean jj_3R_vec_const_306_3_75()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_vec_const_306_3_76()) {
    jj_scanpos = xsp;
    if (jj_3R_vec_const_307_3_77()) return true;
    }
    return false;
  }

  static private boolean jj_3R_vec_const_306_3_76()
 {
    if (jj_scan_token(LSQU)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_vec_const_306_36_80()) jj_scanpos = xsp;
    if (jj_scan_token(RSQU)) return true;
    return false;
  }

  static private boolean jj_3R_simple_term_300_3_73()
 {
    if (jj_3R_vec_const_306_3_75()) return true;
    return false;
  }

  static private boolean jj_3R_simple_term_299_3_72()
 {
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  static private boolean jj_3R_simple_term_298_3_71()
 {
    if (jj_scan_token(IDVEC)) return true;
    return false;
  }

  static private boolean jj_3R_simple_term_297_3_68()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_simple_term_297_3_70()) {
    jj_scanpos = xsp;
    if (jj_3R_simple_term_298_3_71()) {
    jj_scanpos = xsp;
    if (jj_3R_simple_term_299_3_72()) {
    jj_scanpos = xsp;
    if (jj_3R_simple_term_300_3_73()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_simple_term_297_3_70()
 {
    if (jj_scan_token(IDNUM)) return true;
    return false;
  }

  static private boolean jj_3R_sum_255_42_49()
 {
    if (jj_3R_add_sub_term_263_7_56()) return true;
    return false;
  }

  static private boolean jj_3R_term_291_3_58()
 {
    if (jj_3R_simple_term_297_3_68()) return true;
    return false;
  }

  static private boolean jj_3_8()
 {
    if (jj_3R_fn_call_128_3_16()) return true;
    return false;
  }

  static private boolean jj_3R_term_289_3_52()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_term_289_3_57()) {
    jj_scanpos = xsp;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3R_term_291_3_58()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_term_289_3_57()
 {
    if (jj_scan_token(LRND)) return true;
    if (jj_3R_expression_249_3_18()) return true;
    if (jj_scan_token(RRND)) return true;
    return false;
  }

  static private boolean jj_3R_sum_256_35_50()
 {
    if (jj_3R_add_sub_term_263_7_56()) return true;
    return false;
  }

  static private boolean jj_3R_unary_283_7_44()
 {
    if (jj_3R_term_289_3_52()) return true;
    return false;
  }

  static private boolean jj_3R_unary_282_7_43()
 {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_unary_281_7_38()) return true;
    return false;
  }

  static private boolean jj_3R_unary_281_7_38()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_unary_281_7_42()) {
    jj_scanpos = xsp;
    if (jj_3R_unary_282_7_43()) {
    jj_scanpos = xsp;
    if (jj_3R_unary_283_7_44()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_unary_281_7_42()
 {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_unary_281_7_38()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_fn_call_128_3_16()) return true;
    return false;
  }

  static private boolean jj_3R_product_274_9_65()
 {
    if (jj_scan_token(MOD)) return true;
    if (jj_3R_unary_281_7_38()) return true;
    return false;
  }

  static private boolean jj_3R_product_273_9_64()
 {
    if (jj_scan_token(DIV)) return true;
    if (jj_3R_unary_281_7_38()) return true;
    return false;
  }

  static private boolean jj_3R_product_272_9_55()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_product_272_9_63()) {
    jj_scanpos = xsp;
    if (jj_3R_product_273_9_64()) {
    jj_scanpos = xsp;
    if (jj_3R_product_274_9_65()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_product_272_9_63()
 {
    if (jj_scan_token(TIMES)) return true;
    if (jj_3R_unary_281_7_38()) return true;
    return false;
  }

  static private boolean jj_3R_comparator_242_38_37()
 {
    if (jj_scan_token(NOTIN)) return true;
    return false;
  }

  static private boolean jj_3R_comparator_241_36_33()
 {
    if (jj_scan_token(GE)) return true;
    return false;
  }

  static private boolean jj_3R_product_270_5_21()
 {
    if (jj_3R_unary_281_7_38()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_product_272_9_55()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_sum_257_18_51()
 {
    if (jj_3R_add_sub_term_263_7_56()) return true;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_identifier_313_3_15()) return true;
    if (jj_scan_token(ASSGN)) return true;
    return false;
  }

  static private boolean jj_3R_add_sub_term_264_7_67()
 {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_product_270_5_21()) return true;
    return false;
  }

  static private boolean jj_3R_add_sub_term_263_7_56()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_add_sub_term_263_7_66()) {
    jj_scanpos = xsp;
    if (jj_3R_add_sub_term_264_7_67()) return true;
    }
    return false;
  }

  static private boolean jj_3R_add_sub_term_263_7_66()
 {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_product_270_5_21()) return true;
    return false;
  }

  static private boolean jj_3R_comparator_242_26_36()
 {
    if (jj_scan_token(IN)) return true;
    return false;
  }

  static private boolean jj_3R_comparator_241_25_32()
 {
    if (jj_scan_token(GREAT)) return true;
    return false;
  }

  static private boolean jj_3R_sum_257_5_41()
 {
    if (jj_3R_product_270_5_21()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_sum_257_18_51()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_7()
 {
    if (jj_scan_token(PLUS)) return true;
    if (jj_3R_product_270_5_21()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_sum_256_35_50()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_sum_255_5_29()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3R_sum_257_5_41()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_product_270_5_21()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_sum_255_42_49()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_comparator_242_14_35()
 {
    if (jj_scan_token(NEQ)) return true;
    return false;
  }

  static private boolean jj_3R_comparator_241_13_31()
 {
    if (jj_scan_token(LE)) return true;
    return false;
  }

  static private boolean jj_3R_expression_249_3_18()
 {
    if (jj_3R_sum_255_5_29()) return true;
    return false;
  }

  static private boolean jj_3R_comparator_242_3_34()
 {
    if (jj_scan_token(EQ)) return true;
    return false;
  }

  static private boolean jj_3R_comparator_240_3_30()
 {
    if (jj_scan_token(LESS)) return true;
    return false;
  }

  static private boolean jj_3R_comparator_240_3_19()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_comparator_240_3_30()) {
    jj_scanpos = xsp;
    if (jj_3R_comparator_241_13_31()) {
    jj_scanpos = xsp;
    if (jj_3R_comparator_241_25_32()) {
    jj_scanpos = xsp;
    if (jj_3R_comparator_241_36_33()) {
    jj_scanpos = xsp;
    if (jj_3R_comparator_242_3_34()) {
    jj_scanpos = xsp;
    if (jj_3R_comparator_242_14_35()) {
    jj_scanpos = xsp;
    if (jj_3R_comparator_242_26_36()) {
    jj_scanpos = xsp;
    if (jj_3R_comparator_242_38_37()) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_3R_expression_249_3_18()) return true;
    if (jj_3R_comparator_240_3_19()) return true;
    return false;
  }

  static private boolean jj_3R_and_clause_220_18_40()
 {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_not_clause_225_3_39()) return true;
    return false;
  }

  static private boolean jj_3R_comparison_235_3_53()
 {
    if (jj_3R_expression_249_3_18()) return true;
    if (jj_3R_comparator_240_3_19()) return true;
    if (jj_3R_expression_249_3_18()) return true;
    return false;
  }

  static private boolean jj_3R_condition_216_18_28()
 {
    if (jj_scan_token(VBAR)) return true;
    if (jj_3R_and_clause_221_3_27()) return true;
    return false;
  }

  static private boolean jj_3R_not_clause_229_3_48()
 {
    if (jj_3R_bool_simple_321_3_54()) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_3R_boolean_call_136_3_20()) return true;
    return false;
  }

  static private boolean jj_3R_not_clause_227_3_47()
 {
    if (jj_scan_token(LRND)) return true;
    if (jj_3R_condition_217_3_17()) return true;
    if (jj_scan_token(RRND)) return true;
    return false;
  }

  static private boolean jj_3R_not_clause_226_3_46()
 {
    if (jj_3R_comparison_235_3_53()) return true;
    return false;
  }

  static private boolean jj_3R_not_clause_225_3_39()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_not_clause_225_3_45()) {
    jj_scanpos = xsp;
    if (jj_3R_not_clause_226_3_46()) {
    jj_scanpos = xsp;
    if (jj_3R_not_clause_227_3_47()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3R_not_clause_229_3_48()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_not_clause_225_3_45()
 {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_not_clause_225_3_39()) return true;
    return false;
  }

  static private boolean jj_3R_and_clause_221_3_27()
 {
    if (jj_3R_not_clause_225_3_39()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_and_clause_220_18_40()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_condition_217_3_17()
 {
    if (jj_3R_and_clause_221_3_27()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_condition_216_18_28()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_boolean_call_136_63_59()
 {
    if (jj_3R_exp_list_142_3_69()) return true;
    return false;
  }

  static private boolean jj_3R_fn_call_130_61_79()
 {
    if (jj_3R_exp_list_142_3_69()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public VNMTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[46];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0xc06001,0x0,0xc06000,0x0,0x0,0x0,0x0,0x0,0x4000000,0x0,0x4000000,0xc06000,0xc06000,0x0,0xc06000,0x4000000,0x4000000,0xc06000,0xc06000,0x4000000,0xc06000,0x0,0x0,0x0,0x80000,0x40000,0x100000,0x400000,0x30000000,0x1fe0,0x6000,0x6000,0x6000,0xc06000,0x6000,0x38000,0x38000,0xc06000,0x400000,0x800000,0x800000,0xc06000,0x30d06000,0x800000,0x0,0x30000000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x3c1d87,0x1d87,0x3c0000,0x1d87,0x1d87,0x380000,0x381d87,0x381d87,0x0,0x380000,0x0,0x2c0000,0x2c0000,0x280000,0x2c0000,0x0,0x0,0x2c0000,0x3e0000,0x0,0x3e0000,0x380000,0x70,0x70,0x0,0x0,0x0,0x0,0x100000,0x0,0x0,0x0,0x0,0x2c0000,0x0,0x0,0x0,0x2c0000,0x0,0x2c0000,0x2c0000,0x2c0000,0x3c0000,0x0,0x380000,0x100000,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[9];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public VNM(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public VNM(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new VNMTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public VNM(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new VNMTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new VNMTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public VNM(VNMTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(VNMTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 46; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[55];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 46; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 55; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 9; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			   case 8: jj_3_9(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

                  }
