/* Generated By:JJTree: Do not edit this line. ASTAssign.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssign extends SimpleNode {
  public ASTAssign(int id) {
    super(id);
  }

  public ASTAssign(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=67d907217e608e902b5bc110f216a393 (do not edit this line) */
