/* Generated By:JJTree: Do not edit this line. ASTFALSE.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFALSE extends SimpleNode {
  public ASTFALSE(int id) {
    super(id);
  }

  public ASTFALSE(VNM p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(VNMVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=334cc6981e92aa03a701c154b6903be9 (do not edit this line) */
