/* Generated By:JavaCC: Do not edit this line. VNMTreeConstants.java Version 7.0.9 */
public interface VNMTreeConstants
{
  public int JJTVOID = 0;
  public int JJTBODY = 1;
  public int JJTCLAUSE = 2;
  public int JJTVAR_DECL = 3;
  public int JJTFN_DECL = 4;
  public int JJTIDENT_LIST = 5;
  public int JJTFN_CALL = 6;
  public int JJTIDNUM = 7;
  public int JJTIDVEC = 8;
  public int JJTBOOLEAN_CALL = 9;
  public int JJTIDBOOL = 10;
  public int JJTEXP_LIST = 11;
  public int JJTCONDITION_LIST = 12;
  public int JJTRETURN = 13;
  public int JJTPRINT = 14;
  public int JJTPRINT_LN = 15;
  public int JJTSTRING = 16;
  public int JJTASSIGN = 17;
  public int JJTIF = 18;
  public int JJTNULL = 19;
  public int JJTFOR = 20;
  public int JJTWHILE = 21;
  public int JJTOR = 22;
  public int JJTAND = 23;
  public int JJTNOT = 24;
  public int JJTCOMPARISON = 25;
  public int JJTLE = 26;
  public int JJTLEQ = 27;
  public int JJTGRE = 28;
  public int JJTGEQ = 29;
  public int JJTEQ = 30;
  public int JJTNEQ = 31;
  public int JJTIN = 32;
  public int JJTNOTIN = 33;
  public int JJTNEG = 34;
  public int JJTSUM = 35;
  public int JJTPOS = 36;
  public int JJTMUL = 37;
  public int JJTDIV = 38;
  public int JJTMOD = 39;
  public int JJTNUMBER = 40;
  public int JJTVEC_CONST = 41;
  public int JJTTRUE = 42;
  public int JJTFALSE = 43;


  public String[] jjtNodeName = {
    "void",
    "body",
    "clause",
    "var_decl",
    "fn_decl",
    "ident_list",
    "fn_call",
    "idnum",
    "idvec",
    "boolean_call",
    "idbool",
    "exp_list",
    "condition_list",
    "Return",
    "Print",
    "Print_ln",
    "string",
    "Assign",
    "If",
    "NULL",
    "For",
    "While",
    "or",
    "and",
    "not",
    "comparison",
    "le",
    "leq",
    "gre",
    "geq",
    "eq",
    "neq",
    "in",
    "notin",
    "neg",
    "sum",
    "pos",
    "mul",
    "div",
    "mod",
    "number",
    "vec_const",
    "TRUE",
    "FALSE",
  };
}
/* JavaCC - OriginalChecksum=9530ac14eaa35e39b1ebf5140c1dec62 (do not edit this line) */
