/* Generated By:JavaCC: Do not edit this line. VNMEval.java Version 7.0.9 */
public class VNMEval implements VNMVisitor{
  public Object defaultVisit(SimpleNode node, Object data) throws Exception{
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTbody node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTclause node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTvar_decl node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTfn_decl node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTident_list node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTfn_call node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTboolean_call node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTexp_list node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTcondition_list node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTReturn node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  
  public Object visit(ASTPrint node, Object data) throws Exception{
    int children = node.jjtGetNumChildren();
    for (int i=0; i<children; i++)
      System.out.print(node.jjtGetChild(i).jjtAccept(this,null));
		return null;
  }
  public Object visit(ASTPrint_ln node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  
  public Object visit(ASTAssign node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTIf node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTNULL node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTFor node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhile node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTor node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTand node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTnot node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTcomparison node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTle node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTleq node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTgre node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTgeq node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTeq node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTneq node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTin node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTnotin node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTsum node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTneg node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTpos node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTmul node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTdiv node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTmod node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTvec_const node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTTRUE node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTFALSE node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTidvec node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTidnum node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTidbool node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTnumber node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTstring node, Object data) throws Exception{
    return (String)(node.jjtGetValue());
  }
}
/* JavaCC - OriginalChecksum=22d58c5389ead436110ed9c53d7f4358 (do not edit this line) */
